/**
 * `forge-sim dev` command — the one-command Forge development experience.
 *
 * Reads manifest.yml, detects UIKit vs Custom UI, boots the simulator,
 * starts a WebSocket bridge for RPC, and launches Vite with the renderer.
 *
 * UIKit flow:
 *   1. Dev's @forge/react app code runs in browser (CDT debuggable)
 *   2. @forge/react reconciler produces ForgeDoc via bridge
 *   3. Bridge shim keeps ForgeDoc local (no server round-trip for renders)
 *   4. ForgeDocRenderer maps ForgeDoc → real Atlaskit components
 *   5. Backend calls (invoke, requestJira, etc.) route via WebSocket to simulator
 *
 * Custom UI flow:
 *   1. Dev's React app renders to DOM directly (it's a normal web app)
 *   2. @forge/bridge aliased to our shim
 *   3. Backend calls route via WebSocket to simulator
 *   4. No ForgeDoc, no Atlaskit mapping needed
 */

import { resolve, join, relative, dirname } from 'node:path';
import { existsSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ForgeSimulator } from './simulator.js';
import { deploy } from './deployer.js';
import { createDevServer } from './dev-server.js';
import { parseManifest, type ParsedManifest, type ManifestUIModule, BACKGROUND_SCRIPT_TYPES, getCompatibleBackgroundScripts } from './manifest.js';
import { saveState, loadState, hasPersistedState, getSQLDumpPath } from './persistence.js';
import { buildDefaultContext, buildForgeContext, type RenderContextOptions } from './context.js';
import { createWebTriggerHandler } from './web-trigger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface DevCommandOptions {
  appDir: string;
  port: number;
  wsPort: number;
  open: boolean;
  moduleKey?: string;
  /** Start fresh — don't restore persisted state */
  clean?: boolean;
  /** Enable React.StrictMode (off by default — Atlaskit portals break under it) */
  strictMode?: boolean;
  /** Upstream dev server URL for proxy mode (e.g., http://localhost:3000) */
  proxy?: string;
  /** Context options for the rendered module (issue key, content ID, etc.) */
  renderContext?: RenderContextOptions;
}

// ── UI Module Detection ──────────────────────────────────────────────────

export interface DetectedModule {
  module: ManifestUIModule;
  resourcePath: string;
  mode: 'uikit' | 'customui';
}

/**
 * Detect whether a UI module uses UIKit or Custom UI.
 *
 * UIKit modules:
 *   - Have a resource that points to a file importing @forge/react
 *   - The resource file calls ForgeReconciler.render()
 *
 * Custom UI modules:
 *   - Have a resource that points to a directory with index.html
 *   - Or a file that doesn't import @forge/react
 */
export function detectModuleType(appDir: string, manifest: ParsedManifest, mod: ManifestUIModule): DetectedModule | null {
  if (!mod.resourceKey) {
    // No resource = server-only module (no UI to render)
    return null;
  }

  const resource = manifest.resources.get(mod.resourceKey);
  if (!resource) return null;

  const resourcePath = resolve(appDir, resource.path);

  // Check if it's a directory with index.html (Custom UI)
  if (existsSync(join(resourcePath, 'index.html'))) {
    return { module: mod, resourcePath, mode: 'customui' };
  }

  // Check if the resource points to a file
  const possibleFiles = [
    resourcePath,
    resourcePath + '.tsx',
    resourcePath + '.ts',
    resourcePath + '.jsx',
    resourcePath + '.js',
    join(resourcePath, 'index.tsx'),
    join(resourcePath, 'index.ts'),
    join(resourcePath, 'index.jsx'),
    join(resourcePath, 'index.js'),
  ];

  for (const filePath of possibleFiles) {
    if (existsSync(filePath)) {
      // Read file to check for @forge/react imports (UIKit indicator)
      try {
        const content = readFileSync(filePath, 'utf-8');
        if (content.includes('@forge/react') || content.includes('ForgeReconciler')) {
          return { module: mod, resourcePath: filePath, mode: 'uikit' };
        }
      } catch {}

      // If no @forge/react import, assume Custom UI
      return { module: mod, resourcePath: filePath, mode: 'customui' };
    }
  }

  return null;
}

// ── Entry Point Generation ────────────────────────────────────────────────

function generateUIKitEntry(appResourcePath: string, wsPort: number, strictMode: boolean): string {
  const shellElement = 'React.createElement(ForgeSimShell)';
  const rootElement = strictMode
    ? `React.createElement(React.StrictMode, null, ${shellElement})`
    : shellElement;

  return `
/**
 * Auto-generated by forge-sim dev
 * DO NOT EDIT — this file is regenerated on every run
 */

// Use dynamic imports to guarantee execution order:
// 1. Bridge shim installs globalThis.__bridge
// 2. Dev's app code runs (calls ForgeReconciler.render → produces ForgeDoc)
// 3. React DOM shell mounts (picks up ForgeDoc via onReconcile listener)

async function boot() {
  // 1. Install bridge shim — must happen before any @forge/react code
  const bridge = await import('forge-sim/renderer/bridge');
  bridge.configure({ wsUrl: 'ws://localhost:${wsPort}' });

  // 2. Import the developer's app — triggers ForgeReconciler.render()
  //    The bridge shim buffers the ForgeDoc so step 3 can pick it up
  await import('${appResourcePath}');

  // 3. Mount the Atlaskit renderer shell
  const React = await import('react');
  const ReactDOM = await import('react-dom/client');
  const { ForgeSimShell } = await import('forge-sim/renderer/ForgeSimShell');

  ReactDOM.createRoot(document.getElementById('root')!).render(
    ${rootElement}
  );
}

boot().catch((err) => {
  console.error('[forge-sim] Boot failed:', err);
  document.getElementById('root')!.innerHTML =
    '<div style="padding:40px;font-family:monospace;color:#de350b">' +
    '<h2>⚠️ forge-sim failed to start</h2>' +
    '<pre>' + (err.stack || err.message || err) + '</pre></div>';
});
`;
}

/**
 * Generate a self-contained inline script that installs window.__bridge
 * for pre-built Custom UI apps. This runs before any bundled app code,
 * so @forge/bridge's getCallBridge() finds our bridge immediately.
 */
export function generateBridgeInlineScript(wsPort: number, defaultModuleKey?: string): string {
  return `
(function() {
  var S = {
    ws: null, wsReady: false, wsUrl: 'ws://localhost:${wsPort}',
    pendingRequests: {}, requestCounter: 0, reconcileListeners: [], lastForgeDoc: null,
    eventListeners: {}
  };
  window.__forgeSim = S;

  function ensureConnection() {
    if (S.ws && S.wsReady) return Promise.resolve();
    return new Promise(function(resolve, reject) {
      if (S.ws && S.ws.readyState === WebSocket.CONNECTING) {
        S.ws.addEventListener('open', function() { resolve(); }, { once: true });
        return;
      }
      S.ws = new WebSocket(S.wsUrl);
      S.ws.onopen = function() { S.wsReady = true; resolve(); };
      S.ws.onmessage = function(event) {
        try {
          var msg = JSON.parse(event.data);
          // History commands from server (UIKit push/replace/go)
          if (msg.type === 'historyCommand') {
            handleHistoryCommand(msg);
            return;
          }
          // Forge events relay (from other modules via server)
          if (msg.type === 'forgeEvent') {
            var eventKey = msg.isPublic ? ('public:' + msg.eventName) : msg.eventName;
            var cbs = S.eventListeners[eventKey];
            if (cbs) { cbs.forEach(function(cb) { try { cb(msg.payload); } catch(e) { console.error(e); } }); }
            return;
          }
          if (msg.requestId && S.pendingRequests[msg.requestId]) {
            var pending = S.pendingRequests[msg.requestId];
            delete S.pendingRequests[msg.requestId];
            if (msg.error) pending.reject(new Error(msg.error));
            else pending.resolve(msg.result);
          }
        } catch(e) { console.warn('[forge-sim] Failed to parse WS message:', e); }
      };
      S.ws.onclose = function() {
        S.wsReady = false;
        Object.keys(S.pendingRequests).forEach(function(id) {
          S.pendingRequests[id].reject(new Error('WebSocket disconnected'));
          delete S.pendingRequests[id];
        });
        setTimeout(function() { ensureConnection(); }, 2000);
      };
      S.ws.onerror = function() { S.wsReady = false; reject(new Error('WebSocket connection failed')); };
    });
  }

  function rpc(method, params) {
    return ensureConnection().then(function() {
      var requestId = 'rpc-' + (++S.requestCounter) + '-' + Date.now();
      return new Promise(function(resolve, reject) {
        var timeout = setTimeout(function() {
          delete S.pendingRequests[requestId];
          reject(new Error('RPC timeout: ' + method));
        }, 30000);
        S.pendingRequests[requestId] = {
          resolve: function(v) { clearTimeout(timeout); resolve(v); },
          reject: function(e) { clearTimeout(timeout); reject(e); }
        };
        S.ws.send(JSON.stringify({ type: 'rpc', requestId: requestId, method: method, params: params || {} }));
      });
    });
  }

  function getModuleKeyFromURL() {
    var match = window.location.pathname.match(/\\/module\\/([^/]+)/);
    return match ? match[1] : ${defaultModuleKey ? `'${defaultModuleKey}'` : 'undefined'};
  }

  function callBridge(cmd, data) {
    switch(cmd) {
      case 'reconcile':
        if (data && data.forgeDoc) {
          S.lastForgeDoc = data.forgeDoc;
          S.reconcileListeners.forEach(function(l) { try { l(data.forgeDoc); } catch(e) { console.warn('[forge-sim] Reconcile listener error:', e); } });
        }
        return Promise.resolve();
      case 'invoke':
        if (data && data.invokeType && data.invokeType.startsWith('ui-') && data.invokeType.endsWith('-fetch')) {
          return rpc('invokeRemote', {
            path: data.path,
            method: data.method,
            headers: data.headers,
            body: data.body,
            moduleKey: getModuleKeyFromURL()
          });
        }
        return rpc('invoke', { functionKey: data && data.functionKey, payload: data && data.payload, moduleKey: getModuleKeyFromURL() });
      case 'fetchProduct':
        return rpc('fetchProduct', {
          product: data && data.product, restPath: data && data.restPath,
          fetchRequestInit: data && data.fetchRequestInit
        });
      case 'fetchRemote':
        return rpc('fetchRemote', {
          remoteKey: data && data.remoteKey,
          fetchRequestInit: data && data.fetchRequestInit
        });
      case 'getContext':
        return rpc('getContext', { moduleKey: getModuleKeyFromURL() });
      case 'submit':
        return rpc('viewSubmit', { payload: data && data.payload || data });
      case 'close':
        return rpc('viewClose', { payload: data && data.payload || data });
      case 'createHistory':
        return Promise.resolve((function() {
          var listeners = [];
          var blockers = [];
          var action = 'POP';

          function parsePath(path) {
            if (typeof path === 'object') return { pathname: path.pathname || '/', search: path.search || '', hash: path.hash || '' };
            var p = path || '/';
            var searchIdx = p.indexOf('?');
            var hashIdx = p.indexOf('#');
            var pathname = p, search = '', hash = '';
            if (hashIdx >= 0) { hash = p.slice(hashIdx); p = p.slice(0, hashIdx); }
            if (searchIdx >= 0) { search = p.slice(searchIdx); pathname = p.slice(0, searchIdx); }
            else { pathname = p; }
            return { pathname: pathname, search: search, hash: hash };
          }

          function createLocation(to, state) {
            var parsed = (typeof to === 'string') ? parsePath(to) : to;
            return {
              pathname: parsed.pathname || '/',
              search: parsed.search || '',
              hash: parsed.hash || '',
              state: state === undefined ? null : state,
              key: Math.random().toString(36).slice(2, 10)
            };
          }

          function getCurrentLocation() {
            return {
              pathname: window.location.pathname,
              search: window.location.search,
              hash: window.location.hash,
              state: window.history.state,
              key: (window.history.state && window.history.state.__key) || 'default'
            };
          }

          var history = {
            action: action,
            location: getCurrentLocation(),
            createHref: function(to) {
              if (typeof to === 'string') return to;
              return (to.pathname || '') + (to.search || '') + (to.hash || '');
            },
            push: function(to, state) {
              var loc = createLocation(to, state);
              var update = { action: 'PUSH', location: loc };
              for (var i = 0; i < blockers.length; i++) {
                var blocked = false;
                blockers[i]({ action: 'PUSH', location: loc, retry: function() { history.push(to, state); } });
                blocked = true;
                if (blocked) return;
              }
              var stateObj = state === undefined ? null : state;
              if (stateObj && typeof stateObj === 'object') stateObj = Object.assign({}, stateObj, { __key: loc.key });
              else stateObj = { __key: loc.key };
              window.history.pushState(stateObj, '', history.createHref(loc));
              history.action = 'PUSH';
              history.location = loc;
              listeners.forEach(function(fn) { try { fn(update); } catch(e) { console.error(e); } });
            },
            replace: function(to, state) {
              var loc = createLocation(to, state);
              var update = { action: 'REPLACE', location: loc };
              for (var i = 0; i < blockers.length; i++) {
                blockers[i]({ action: 'REPLACE', location: loc, retry: function() { history.replace(to, state); } });
                return;
              }
              var stateObj = state === undefined ? null : state;
              if (stateObj && typeof stateObj === 'object') stateObj = Object.assign({}, stateObj, { __key: loc.key });
              else stateObj = { __key: loc.key };
              window.history.replaceState(stateObj, '', history.createHref(loc));
              history.action = 'REPLACE';
              history.location = loc;
              listeners.forEach(function(fn) { try { fn(update); } catch(e) { console.error(e); } });
            },
            go: function(delta) { window.history.go(delta); },
            back: function() { window.history.go(-1); },
            forward: function() { window.history.go(1); },
            listen: function(fn) {
              listeners.push(fn);
              return function() { listeners = listeners.filter(function(l) { return l !== fn; }); };
            },
            block: function(fn) {
              blockers.push(fn);
              return function() { blockers = blockers.filter(function(b) { return b !== fn; }); };
            }
          };

          window.addEventListener('popstate', function() {
            history.action = 'POP';
            history.location = getCurrentLocation();
            var update = { action: 'POP', location: history.location };
            listeners.forEach(function(fn) { try { fn(update); } catch(e) { console.error(e); } });
          });

          return history;
        })());
      case 'emit':
        // Dispatch locally
        var emitKey = data && data.event;
        var emitCbs = S.eventListeners[emitKey];
        if (emitCbs) { emitCbs.forEach(function(cb) { try { cb(data.payload); } catch(e) { console.error(e); } }); }
        // Send to server for cross-module relay
        if (S.ws && S.wsReady) {
          S.ws.send(JSON.stringify({ type: 'forgeEvent', eventName: emitKey, payload: data.payload, isPublic: false }));
        }
        return Promise.resolve();
      case 'on':
        var onKey = data && data.event;
        if (!S.eventListeners[onKey]) S.eventListeners[onKey] = [];
        S.eventListeners[onKey].push(data.callback);
        return Promise.resolve({ unsubscribe: function() {
          S.eventListeners[onKey] = (S.eventListeners[onKey] || []).filter(function(cb) { return cb !== data.callback; });
        }});
      case 'emitPublic':
        var emitPubKey = 'public:' + (data && data.event);
        var emitPubCbs = S.eventListeners[emitPubKey];
        if (emitPubCbs) { emitPubCbs.forEach(function(cb) { try { cb(data.payload); } catch(e) { console.error(e); } }); }
        if (S.ws && S.wsReady) {
          S.ws.send(JSON.stringify({ type: 'forgeEvent', eventName: data.event, payload: data.payload, isPublic: true }));
        }
        return Promise.resolve();
      case 'onPublic':
        var onPubKey = 'public:' + (data && data.event);
        if (!S.eventListeners[onPubKey]) S.eventListeners[onPubKey] = [];
        S.eventListeners[onPubKey].push(data.callback);
        return Promise.resolve({ unsubscribe: function() {
          S.eventListeners[onPubKey] = (S.eventListeners[onPubKey] || []).filter(function(cb) { return cb !== data.callback; });
        }});
      case 'refresh':
        window.location.reload();
        return Promise.resolve();
      case 'enableTheming':
        return Promise.resolve();
      default:
        console.warn('[forge-sim bridge] Unhandled command: ' + cmd);
        return Promise.resolve();
    }
  }

  window.__bridge = { callBridge: callBridge };

  // ── History command handler (server → browser) ──────────────────────
  function getCurrentLocation() {
    return {
      pathname: window.location.pathname,
      search: window.location.search,
      hash: window.location.hash,
      state: window.history.state,
      key: (window.history.state && window.history.state.__key) || 'default'
    };
  }

  function handleHistoryCommand(msg) {
    var requestId = msg.requestId;
    var cmd = msg.cmd;
    var data = msg.data;
    var loc, stateObj, href;

    if (cmd === 'history.push') {
      loc = typeof data.to === 'string' ? data.to : ((data.to.pathname || '') + (data.to.search || '') + (data.to.hash || ''));
      stateObj = data.state || null;
      if (stateObj && typeof stateObj === 'object') stateObj.__key = Math.random().toString(36).slice(2, 10);
      else stateObj = { __key: Math.random().toString(36).slice(2, 10) };
      window.history.pushState(stateObj, '', loc);
    } else if (cmd === 'history.replace') {
      loc = typeof data.to === 'string' ? data.to : ((data.to.pathname || '') + (data.to.search || '') + (data.to.hash || ''));
      stateObj = data.state || null;
      if (stateObj && typeof stateObj === 'object') stateObj.__key = Math.random().toString(36).slice(2, 10);
      else stateObj = { __key: Math.random().toString(36).slice(2, 10) };
      window.history.replaceState(stateObj, '', loc);
    } else if (cmd === 'history.go') {
      window.history.go(data.delta);
      // popstate will fire asynchronously — ack will come from the popstate handler
      return;
    }

    // Acknowledge with updated location
    var action = cmd === 'history.push' ? 'PUSH' : 'REPLACE';
    if (S.ws && S.wsReady) {
      S.ws.send(JSON.stringify({ type: 'historyAck', requestId: requestId, action: action, location: getCurrentLocation() }));
    }
  }

  // Listen for browser back/forward → notify server
  window.addEventListener('popstate', function() {
    if (S.ws && S.wsReady) {
      S.ws.send(JSON.stringify({ type: 'historyEvent', action: 'POP', location: getCurrentLocation() }));
    }
  });

  // Pre-connect WebSocket so it's ready when the app loads
  ensureConnection();
})();
`;
}

function generateCustomUIEntry(_appResourcePath: string, wsPort: number): string {
  // For Custom UI, we generate a small bootstrap script that Vite injects.
  // The dev's index.html is served directly — this script just configures the bridge.
  return `
/**
 * Auto-generated by forge-sim dev (Custom UI mode)
 * Configures the @forge/bridge shim before the app loads.
 */
import { configure } from 'forge-sim/renderer/bridge-shim';
configure({ wsUrl: 'ws://localhost:${wsPort}' });
`;
}

function generateIndexHtml(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title} — forge-sim</title>
    <style>
      body { margin: 0; background: #f4f5f7; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./entry.tsx"></script>
    ${BACKGROUND_SCRIPT_IFRAME_INJECTOR}
  </body>
</html>`;
}

/**
 * Inline script that reads ?bg=key1,key2 from the URL and injects
 * hidden iframes for each background script module.
 */
const BACKGROUND_SCRIPT_IFRAME_INJECTOR = `<script>
(function() {
  var params = new URLSearchParams(window.location.search);
  var bg = params.get('bg');
  if (!bg) return;
  bg.split(',').forEach(function(key) {
    if (!key) return;
    var iframe = document.createElement('iframe');
    iframe.src = '/module/' + key + '/';
    iframe.style.display = 'none';
    iframe.setAttribute('data-forge-sim-bg', key);
    iframe.setAttribute('aria-hidden', 'true');
    document.body.appendChild(iframe);
  });
})();
</script>`;


// ── Module Picker Page ────────────────────────────────────────────────────

export function generateModulePickerHtml(modules: DetectedModule[]): string {
  // Separate UI modules from background scripts
  const uiModules = modules.filter((m) => !BACKGROUND_SCRIPT_TYPES.has(m.module.type));
  const bgModules = modules.filter((m) => BACKGROUND_SCRIPT_TYPES.has(m.module.type));

  const rows = uiModules.map((m) => {
    const modeLabel = m.mode === 'uikit' ? 'UIKit 2' : 'Custom UI';
    const modeBadge = m.mode === 'uikit'
      ? '<span style="background:#0052CC;color:#fff;padding:2px 8px;border-radius:3px;font-size:12px">UIKit</span>'
      : '<span style="background:#00875A;color:#fff;padding:2px 8px;border-radius:3px;font-size:12px">Custom UI</span>';

    // Find compatible background scripts for this module
    const compatBg = getCompatibleBackgroundScripts(m.module.type, modules.map((d) => d.module));
    const bgCheckboxes = compatBg.map((bg) =>
      `<label style="display:inline-flex;align-items:center;gap:4px;font-size:12px;color:#6B778C;margin-top:6px;cursor:pointer" onclick="event.preventDefault();event.stopPropagation();this.querySelector('input').click()">
        <input type="checkbox" checked data-bg-key="${bg.key}" onclick="event.stopPropagation()" style="cursor:pointer" />
        ${bg.key} <span style="color:#97A0AF">(${bg.type.split(':').pop()})</span>
      </label>`
    ).join(' ');

    // Encode compatible BG keys as a data attribute for the link
    const bgKeysAttr = compatBg.length > 0 ? ` data-bg-keys="${compatBg.map((b) => b.key).join(',')}"` : '';

    return `
      <a href="/module/${m.module.key}/" ${bgKeysAttr} style="display:block;padding:16px 20px;border:1px solid #DFE1E6;border-radius:8px;margin-bottom:12px;text-decoration:none;color:inherit;transition:box-shadow 0.15s" onclick="handleModuleClick(event, this)">
        <div style="display:flex;align-items:center;gap:12px">
          <div style="flex:1">
            <div style="font-size:16px;font-weight:600;color:#172B4D">${m.module.key}</div>
            <div style="font-size:13px;color:#6B778C;margin-top:4px">${m.module.type}${m.module.title ? ' — ' + m.module.title : ''}</div>
            ${bgCheckboxes ? `<div style="margin-top:4px">${bgCheckboxes}</div>` : ''}
          </div>
          ${modeBadge}
        </div>
      </a>`;
  }).join('');

  // Show background scripts in a separate section if they exist but aren't linked to any UI module
  const orphanBg = bgModules.filter((bg) => {
    // Check if any UI module in the list has this as a compatible background script
    return !uiModules.some((ui) =>
      getCompatibleBackgroundScripts(ui.module.type, modules.map((d) => d.module))
        .some((b) => b.key === bg.module.key)
    );
  });
  const orphanSection = orphanBg.length > 0
    ? `<div style="margin-top:24px;padding:16px 20px;border:1px solid #DFE1E6;border-radius:8px;background:#FAFBFC">
        <div style="font-size:14px;font-weight:600;color:#6B778C;margin-bottom:8px">Background Scripts (no matching UI module)</div>
        ${orphanBg.map((bg) => `<div style="font-size:13px;color:#97A0AF;margin-bottom:4px">${bg.module.key} — ${bg.module.type}</div>`).join('')}
      </div>`
    : '';

  const uiCount = uiModules.length;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>forge-sim — Module Picker</title>
  <style>
    body { margin:0; background:#F4F5F7; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,sans-serif; }
    a:hover { box-shadow:0 2px 8px rgba(0,0,0,0.12) !important; }
  </style>
</head>
<body>
  <div style="max-width:600px;margin:60px auto;padding:0 20px">
    <h1 style="font-size:24px;color:#172B4D;margin-bottom:8px">forge-sim dev</h1>
    <p style="color:#6B778C;margin-bottom:32px">${uiCount} UI module${uiCount !== 1 ? 's' : ''} detected. Pick one to render:</p>
    ${rows}
    ${orphanSection}
    <div style="margin-top:24px;text-align:center">
      <a href="/__tools/" style="color:#0052CC;font-size:13px">Open Dev Tools</a>
    </div>
  </div>
  <script>
    function handleModuleClick(event, el) {
      // Check which background script checkboxes are checked
      var checkboxes = el.querySelectorAll('input[data-bg-key]');
      var enabledBg = [];
      checkboxes.forEach(function(cb) { if (cb.checked) enabledBg.push(cb.getAttribute('data-bg-key')); });
      var url = el.getAttribute('href');
      if (enabledBg.length > 0) {
        url += '?bg=' + enabledBg.join(',');
      }
      event.preventDefault();
      window.location.href = url;
    }
  </script>
</body>
</html>`;
}

// ── Multi-Module Vite Middleware ───────────────────────────────────────────

/**
 * Installs Vite middleware that:
 * - `/` → module picker page
 * - `/module/<key>/` → serves that module's entry
 * - Everything else passes through to Vite (including __tools)
 */
export function installModuleRouting(
  viteServer: any,
  modules: DetectedModule[],
  tempDir: string,
): void {
  const modulesByKey = new Map(modules.map((m) => [m.module.key, m]));

  const middleware = (req: any, res: any, next: any) => {
    const url = new URL(req.url ?? '/', 'http://localhost');

    // Root → module picker (but only for exact '/' with no file extension)
    if (url.pathname === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html', 'Cache-Control': 'no-cache' });
      res.end(generateModulePickerHtml(modules));
      return;
    }

    // /module/<key>/ → rewrite to serve that module's index.html via Vite
    const match = url.pathname.match(/^\/module\/([^/]+)(\/.*)?$/);
    if (match) {
      const key = match[1];
      const rest = match[2] || '/';
      const mod = modulesByKey.get(key);

      if (!mod) {
        res.writeHead(404, { 'Content-Type': 'text/html' });
        res.end(`<h1>404</h1><p>Module "${key}" not found.</p><p><a href="/">Back to module picker</a></p>`);
        return;
      }

      if (mod.mode === 'uikit') {
        // Rewrite URL to serve from the module's temp subdirectory
        // /module/<key>/ → /<key>/index.html
        // /module/<key>/entry.tsx → /<key>/entry.tsx
        if (rest === '/' || rest === '/index.html') {
          req.url = `/${key}/index.html`;
        } else {
          req.url = `/${key}${rest}`;
        }
      } else {
        // Custom UI — rewrite to serve from /_customui_<key>/ virtual prefix
        // The Vite alias handles mapping this to the actual resource directory
        if (rest === '/' || rest === '/index.html') {
          req.url = `/_customui_${key}/index.html`;
        } else {
          req.url = `/_customui_${key}${rest}`;
        }
      }
    }

    next();
  };

  // Prepend to Vite's middleware stack (before Vite's catch-all)
  const stack = (viteServer.middlewares as any).stack;
  if (Array.isArray(stack)) {
    stack.unshift({ route: '', handle: middleware });
  } else {
    viteServer.middlewares.use(middleware);
  }
}

// ── Vite Config Builder ───────────────────────────────────────────────────

/**
 * Build the Vite config as a JS object — passed directly to createServer().
 * No config file needed, so Vite doesn't have to resolve 'vite' or plugin
 * imports from the app's directory.
 *
 * Multi-module mode: Vite root is the temp dir containing per-module
 * subdirectories (<key>/entry.tsx + index.html for UIKit modules).
 * Custom UI modules are served via aliases mapping /_customui_<key>/ paths
 * to their resource directories.
 */
async function buildViteConfig(opts: {
  appDir: string;
  tempDir: string;
  modules: DetectedModule[];
  wsPort: number;
  port: number;
  forgeSimRoot: string;
}): Promise<any> {
  const { appDir, tempDir, modules, wsPort, port, forgeSimRoot } = opts;
  const shimPath = join(forgeSimRoot, 'renderer', 'src', 'bridge', 'forge-bridge-shim.ts');
  const bridgeBarrel = join(forgeSimRoot, 'renderer', 'src', 'bridge', 'index.ts');

  const rendererNodeModules = join(forgeSimRoot, 'renderer', 'node_modules');
  const mainNodeModules = join(forgeSimRoot, 'node_modules');
  const appNodeModules = join(appDir, 'node_modules');

  // Import the plugin directly — it's in forge-sim's node_modules
  const reactPlugin = (await import('@vitejs/plugin-react')).default;

  // Build alias map: standard aliases + Custom UI resource directories
  const aliases: Record<string, string> = {
    '@forge/bridge': shimPath,
    'forge-sim/renderer/bridge': bridgeBarrel,
    'forge-sim/renderer/bridge-shim': shimPath,
    'forge-sim/renderer/ForgeDocRenderer': join(forgeSimRoot, 'renderer', 'src', 'ForgeDocRenderer.tsx'),
    'forge-sim/renderer/ForgeSimShell': join(forgeSimRoot, 'renderer', 'src', 'ForgeSimShell.tsx'),
  };

  // Collect all directories Vite needs fs access to
  const fsAllow = [forgeSimRoot, appDir, tempDir];

  // For Custom UI modules, add a Vite plugin to resolve /_customui_<key>/ paths
  const customUiModules = modules.filter((m) => m.mode === 'customui');
  for (const m of customUiModules) {
    fsAllow.push(m.resourcePath);
  }

  // Custom UI rewrite plugin — maps /_customui_<key>/path to the resource directory
  const customUiPlugin = {
    name: 'forge-sim-custom-ui',
    configureServer(server: any) {
      server.middlewares.use((req: any, _res: any, next: any) => {
        if (!req.url) return next();
        const match = req.url.match(/^\/_customui_([^/]+)(\/.*)?$/);
        if (!match) return next();
        const key = match[1];
        const rest = match[2] || '/index.html';
        const mod = modules.find((m) => m.module.key === key && m.mode === 'customui');
        if (!mod) return next();
        // Rewrite to serve from the resource directory
        // For directory-based Custom UI (with index.html), resourcePath is the dir
        const resourceDir = existsSync(join(mod.resourcePath, 'index.html'))
          ? mod.resourcePath
          : dirname(mod.resourcePath);
        req.url = rest;
        // Use Vite's static file serving by changing the url
        // We need to actually serve the file from the right directory
        const filePath = join(resourceDir, rest);
        if (existsSync(filePath)) {
          const ext = filePath.split('.').pop() || '';
          const mimeTypes: Record<string, string> = {
            html: 'text/html', js: 'application/javascript', ts: 'application/javascript',
            tsx: 'application/javascript', jsx: 'application/javascript',
            css: 'text/css', json: 'application/json', svg: 'image/svg+xml',
            png: 'image/png', jpg: 'image/jpeg', ico: 'image/x-icon',
          };

          // For HTML files, inject the bridge shim before any app scripts
          if (ext === 'html') {
            let html = readFileSync(filePath, 'utf-8');
            const bridgeScript = generateBridgeInlineScript(wsPort);
            // Inject right after <head> (before any other scripts)
            html = html.replace(/<head([^>]*)>/i, `<head$1>\n<script>${bridgeScript}</script>`);
            // Inject background script iframe loader before </body>
            html = html.replace(/<\/body>/i, `${BACKGROUND_SCRIPT_IFRAME_INJECTOR}\n</body>`);
            _res.writeHead(200, { 'Content-Type': 'text/html' });
            _res.end(html);
            return;
          }

          const content = readFileSync(filePath);
          _res.writeHead(200, { 'Content-Type': mimeTypes[ext] || 'application/octet-stream' });
          _res.end(content);
          return;
        }
        next();
      });
    },
  };

  return {
    configFile: false as const,
    root: tempDir,
    plugins: [reactPlugin(), customUiPlugin],
    server: {
      port,
      host: true,
      open: false,
      fs: {
        allow: [...new Set(fsAllow)],
      },
    },
    resolve: {
      alias: aliases,
      modules: [
        rendererNodeModules,
        appNodeModules,
        mainNodeModules,
        'node_modules',
      ],
    },
    define: {
      '__FORGE_SIM_WS_URL__': JSON.stringify(`ws://localhost:${wsPort}`),
      // @atlaskit/editor-core and @atlaskit/renderer deep deps reference
      // process.env (Node global) which doesn't exist in the browser.
      'process.env.NODE_ENV': JSON.stringify('development'),
      'process.env': JSON.stringify({}),
    },
    optimizeDeps: {
      include: ['react', 'react-dom', 'react/jsx-runtime'],
    },
  };
}

// ── Main Dev Command ──────────────────────────────────────────────────────

export async function devCommand(options: DevCommandOptions) {
  const { appDir, port, wsPort, open, moduleKey, clean, strictMode, proxy, renderContext } = options;
  const stateDir = join(appDir, '.forge-sim', 'state');

  console.log('');
  console.log('  🔥 forge-sim dev');
  console.log('  ─────────────────');
  console.log('');

  // 1. Validate app directory
  const manifestPath = join(appDir, 'manifest.yml');
  if (!existsSync(manifestPath)) {
    console.error(`  ❌ No manifest.yml found in ${appDir}`);
    console.error(`     Are you in a Forge app directory?`);
    process.exit(1);
  }

  // 2. Parse manifest
  console.log(`  📋 Reading manifest.yml...`);
  const manifest = await parseManifest(manifestPath);
  console.log(`     App: ${manifest.raw.app?.name ?? manifest.raw.app?.id ?? 'unnamed'}`);
  console.log(`     Functions: ${manifest.functions.size}`);
  console.log(`     UI modules: ${manifest.uiModules.length}`);
  console.log('');

  // 3. Find UI module to render
  const detectedModules: DetectedModule[] = [];
  if (proxy) {
    // Proxy mode: skip resource path validation entirely.
    // The upstream dev server serves the UI — we just need module metadata
    // for routing, endpoint resolution, and context.
    for (const mod of manifest.uiModules) {
      if (moduleKey && mod.key !== moduleKey) continue;
      detectedModules.push({ module: mod, resourcePath: '', mode: 'customui' });
    }
  } else {
    for (const mod of manifest.uiModules) {
      if (moduleKey && mod.key !== moduleKey) continue;
      const detected = detectModuleType(appDir, manifest, mod);
      if (detected) detectedModules.push(detected);
    }
  }

  if (detectedModules.length === 0) {
    console.error(`  ❌ No UI modules found${moduleKey ? ` with key "${moduleKey}"` : ''}`);
    console.error(`     Your manifest needs a module with a resource (jira:issuePanel, etc.)`);
    process.exit(1);
  }

  // In multi-module mode, we serve ALL modules. The --module flag
  // determines the default redirect from / when there's only one.
  const primaryModule = moduleKey
    ? detectedModules.find((d) => d.module.key === moduleKey) ?? detectedModules[0]
    : detectedModules[0];

  for (const mod of detectedModules) {
    const modeLabel = mod.mode === 'uikit' ? 'UIKit 2' : proxy ? 'Proxied' : 'Custom UI';
    console.log(`  🎯 Module: ${mod.module.key} (${mod.module.type}) — ${modeLabel}`);
    if (mod.resourcePath) {
      console.log(`     Resource: ${relative(appDir, mod.resourcePath)}`);
    }
  }
  console.log('');

  // 4. Create simulator and deploy resolvers
  console.log(`  ⚙️  Starting simulator...`);
  const sim = new ForgeSimulator();

  // 4a. Configure SQL restore BEFORE deploy — deploy can trigger scheduled
  // triggers (migrations) which lazily start SQL. The init file must be set
  // before that happens so persisted tables exist when migrations check.
  if (!clean) {
    const sqlDumpPath = await getSQLDumpPath(stateDir);
    if (sqlDumpPath) {
      sim.sql.setInitSQLFilePath(sqlDumpPath);
      // Read table count for logging
      const { readFileSync } = await import('node:fs');
      const dump = readFileSync(sqlDumpPath, 'utf-8');
      const tableCount = (dump.match(/CREATE TABLE/gi) || []).length;
      console.log(`  📂 Restoring SQL state (${tableCount} tables) on MySQL boot`);
    }
  }

  // Set the global simulator instance so that @forge/* shims
  // (loaded via our module hooks) can register handlers directly
  const { setSimulator } = await import('./shims/globals.js');
  setSimulator(sim);

  // Deploy functions (resolvers, triggers, etc.) — these run on the server side
  // For browser mode, we skip loading UI resources (they'll run in the browser)
  try {
    console.log(`     Resolver before deploy: [${[...sim.resolver.getHandlerMap().keys()].join(', ')}]`);
    const deployResult = await deployResolversOnly(sim, appDir, manifest);
    console.log(`     Resolver after deploy: [${[...sim.resolver.getHandlerMap().keys()].join(', ')}]`);
    if (deployResult.loadedFunctions.length > 0) {
      console.log(`     Loaded ${deployResult.loadedFunctions.length} function(s): ${deployResult.loadedFunctions.join(', ')}`);
    }
    if (deployResult.errors.length > 0) {
      for (const err of deployResult.errors) {
        console.warn(`     ⚠️  ${err.functionKey}: ${err.error}`);
      }
    }
  } catch (err: any) {
    console.error(`  ❌ Deploy failed: ${err.message}`);
    if (err.stack) {
      console.error(`     ${err.stack.split('\n').slice(1, 4).join('\n     ')}`);
    }
    console.error(`     The dev server will start but no functions are loaded.`);
    console.error(`     Fix the error above and save — forge-sim will auto-redeploy.`);
  }

  // 4b. Restore KVS state (unless --clean)
  // (SQL restore already configured in 4a via initSQLFilePath)
  if (!clean) {
    if (await hasPersistedState(stateDir)) {
      await loadState(sim, stateDir);
    }
  }

  // 4c. Connect to real Atlassian APIs if credentials exist
  try {
    const { loadCredentials, getDefaultAccount, saveCredentials, upsertAccount } = await import('./auth/credentials.js');
    const store = await loadCredentials(appDir);
    const account = getDefaultAccount(store);

    if (account) {
      // Set up OAuth config for token refresh (only needed for OAuth accounts)
      if (account.authType === 'oauth') {
        try {
          const { getOAuthAppConfig } = await import('./auth/config.js');
          const { setOAuthConfig } = await import('./auth/oauth.js');
          const oauthAppConfig = await getOAuthAppConfig();
          if (oauthAppConfig) setOAuthConfig(oauthAppConfig);
        } catch {}
      }

      sim.productApi.connectRealApis(account, {
        onTokenRefresh: (refreshedAccount) => {
          upsertAccount(store, refreshedAccount);
          saveCredentials(store).catch(() => {});
        },
      });
    } else {
      console.log(`  📡 No Atlassian accounts — using mock APIs`);
      console.log(`     Run 'forge-sim auth' to connect to a real site`);
    }
  } catch (err: any) {
    console.log(`  📡 Using mock APIs (auth load failed: ${err.message})`);
  }

  console.log('');

  // 5. Start WebSocket dev server (for RPC: invoke, fetchProduct, etc.)
  console.log(`  🔌 Starting WebSocket bridge on port ${wsPort}...`);
  // Build context — use full async buildForgeContext if render options were provided
  const moduleContext = renderContext
    ? await buildForgeContext(sim, primaryModule.module.key, primaryModule.module.type, renderContext)
    : buildDefaultContext(primaryModule.module.key, primaryModule.module.type, sim.productApi.connectedAccount);

  const devServer = createDevServer({
    port: wsPort,
    watchDir: appDir,
    simulator: sim,
    context: moduleContext,
  });

  // ── Proxy mode: skip Vite, create reverse proxy instead ─────────────
  if (proxy) {
    const { createProxyServer } = await import('./proxy-server.js');
    const proxyServer = createProxyServer({
      upstream: proxy,
      wsPort,
      defaultModuleKey: primaryModule.module.key,
    });

    // Attach tools middleware and JWKS to the proxy server
    const { attachToolsToVite } = await import('./tools/server.js');

    proxyServer.listen(port);

    const localUrl = `http://localhost:${port}`;

    // Wire up tools API as middleware on the proxy
    const { createApiHandler } = await import('./tools/api.js');
    const apiHandler = createApiHandler(sim, manifest);
    proxyServer.addMiddleware('/__tools', (req, res, pathname, searchParams) => {
      const toolsPath = pathname.slice('/__tools'.length) || '/';
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
      if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return true; }
      if (toolsPath.startsWith('/api/')) {
        const apiUrl = new URL(toolsPath + (searchParams ? '?' + searchParams : ''), 'http://localhost');
        apiHandler(req, res, apiUrl).catch((err: any) => {
          res.writeHead(500, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: err.message }));
        });
        return true;
      }
      // Serve tools UI fallback for non-API /__tools/ paths
      res.writeHead(200, { 'Content-Type': 'text/html', 'Cache-Control': 'no-cache' });
      res.end('<!DOCTYPE html><html><head><title>Forge Sim Tools</title></head><body><h1>Forge Sim Tools</h1><p>Tools UI in proxy mode</p></body></html>');
      return true;
    });

    // Serve JWKS endpoint
    proxyServer.addMiddleware('/__forge', (req, res, pathname) => {
      if (pathname === '/__forge/jwks.json') {
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Cache-Control', 'public, max-age=3600');
        res.writeHead(200);
        res.end(JSON.stringify(sim.fit.getJWKS()));
        return true;
      }
      return false;
    });

    // Web trigger endpoints
    if (manifest.webTriggers.length > 0) {
      const webTriggerHandler = createWebTriggerHandler({ triggers: manifest.webTriggers, simulator: sim });
      proxyServer.addMiddleware('/__trigger', (req, res, pathname) => {
        webTriggerHandler(req, res, pathname);
        return true;
      });
      (globalThis as any).__forgeSim_devPort__ = port;
    }

    // Hook simulator logs (basic — no tools WS in proxy mode)
    sim.onLog((entry: any) => {
      // Logs captured in simulator, viewable via /__tools/api/logs
    });

    console.log('  ─────────────────────────────────────────────');
    console.log('');
    console.log(`  🔥 forge-sim dev (proxy mode)`);
    console.log('');
    console.log(`     Upstream:  ${proxy}`);
    console.log(`     ➜ Local:   ${localUrl}`);
    console.log(`     ➜ WS:      ws://localhost:${wsPort}`);
    console.log(`     ➜ Tools:   ${localUrl}/__tools/`);
    if (manifest.remotes.size > 0) {
      console.log(`     ➜ JWKS:    ${localUrl}/__forge/jwks.json`);
    }
    if (manifest.webTriggers.length > 0) {
      for (const wt of manifest.webTriggers) {
        console.log(`     ➜ Trigger: ${localUrl}/__trigger/${wt.key}`);
      }
    }
    console.log('');
    console.log(`     🔧 Proxying all requests to ${proxy}`);
    console.log(`     💉 Bridge script injected into HTML responses`);
    console.log('');
    console.log('  ─────────────────────────────────────────────');
    console.log('');

    if (open) {
      const { exec: execCmd } = await import('node:child_process');
      const openCommand = process.platform === 'darwin'
        ? `open "${localUrl}"`
        : process.platform === 'win32'
          ? `start "${localUrl}"`
          : `xdg-open "${localUrl}" 2>/dev/null || true`;
      execCmd(openCommand);
    }

    // Graceful shutdown
    let cleaningUp = false;
    const cleanup = async () => {
      if (cleaningUp) return;
      cleaningUp = true;
      console.log('\n  🛑 Shutting down...');
      try { await saveState(sim, stateDir); } catch (err: any) { console.error(`  ⚠️  Failed to save state: ${err.message}`); }
      devServer.close();
      proxyServer.close();
      process.exit(0);
    };
    process.on('SIGINT', () => { cleanup().catch(() => process.exit(1)); });
    process.on('SIGTERM', () => { cleanup().catch(() => process.exit(1)); });
    return;
  }

  // 6. Generate temp project for Vite (multi-module)
  const forgeSimRoot = resolve(__dirname, '..');
  const tempDir = join(appDir, '.forge-sim', 'tmp');

  // Clean up previous temp files (but preserve .forge-sim/state/)
  if (existsSync(tempDir)) {
    rmSync(tempDir, { recursive: true, force: true });
  }
  mkdirSync(tempDir, { recursive: true });
  writeFileSync(join(appDir, '.forge-sim', '.gitignore'), '*\n');

  // Generate per-module entry points
  for (const mod of detectedModules) {
    if (mod.mode === 'uikit') {
      const moduleDir = join(tempDir, mod.module.key);
      mkdirSync(moduleDir, { recursive: true });

      const appResourceRelative = relative(moduleDir, mod.resourcePath).replace(/\\/g, '/');
      const appResourceImportPath = appResourceRelative.startsWith('.') ? appResourceRelative : './' + appResourceRelative;
      const entryContent = generateUIKitEntry(appResourceImportPath, wsPort, !!strictMode);

      writeFileSync(join(moduleDir, 'entry.tsx'), entryContent);
      writeFileSync(join(moduleDir, 'index.html'), generateIndexHtml(
        `${mod.module.key} — ${manifest.raw.app?.name ?? 'Forge App'}`
      ));
    }
    // Custom UI modules don't need temp files — served from resource dir via middleware
  }

  // Write a minimal root index.html (Vite needs one at root)
  writeFileSync(join(tempDir, 'index.html'), generateIndexHtml(manifest.raw.app?.name ?? 'Forge App'));

  const uikitCount = detectedModules.filter((m) => m.mode === 'uikit').length;
  const customUiCount = detectedModules.filter((m) => m.mode === 'customui').length;
  console.log(`  📦 Generated multi-module dev environment (${uikitCount} UIKit, ${customUiCount} Custom UI)`);
  console.log('');

  // 7. Start Vite
  console.log(`  🚀 Starting Vite dev server...`);
  console.log('');

  try {
    const { createServer } = await import('vite');

    const viteConfig = await buildViteConfig({
      appDir,
      tempDir,
      modules: detectedModules,
      wsPort,
      port,
      forgeSimRoot,
    });

    const viteServer = await createServer(viteConfig);

    // Install multi-module routing middleware (before Vite's catch-all)
    installModuleRouting(viteServer, detectedModules, tempDir);

    await viteServer.listen();

    const info = viteServer.resolvedUrls;
    const localUrl = info?.local?.[0] ?? `http://localhost:${port}`;
    const networkUrl = info?.network?.[0];

    console.log('  ─────────────────────────────────────────────');
    console.log('');
    console.log(`  🔥 forge-sim dev server running!`);
    console.log('');
    console.log(`     ${detectedModules.length} module${detectedModules.length !== 1 ? 's' : ''} available`);
    console.log('');
    console.log(`     ➜ Local:   ${localUrl}`);
    if (networkUrl) {
      console.log(`     ➜ Network: ${networkUrl}`);
    }
    console.log(`     ➜ WS:      ws://localhost:${wsPort}`);
    if (manifest.remotes.size > 0) {
      console.log(`     ➜ JWKS:    ${localUrl}/__forge/jwks.json`);
    }

    // 8. Start Forge Sim Tools (uses Vite's HTTP server via middleware)
    const { attachToolsToVite } = await import('./tools/server.js');
    const toolsServer = attachToolsToVite({ sim, manifest, viteServer, appDir });

    // Hook simulator logs into tools broadcast
    sim.onLog((entry: any) => {
      toolsServer.broadcastLog(entry);
    });

    // 8b. Serve FIT JWKS endpoint at /__forge/jwks.json
    const forgeMiddleware = (req: any, res: any, next: any) => {
      const url = new URL(req.url ?? '/', 'http://localhost');
      if (url.pathname === '/__forge/jwks.json') {
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Cache-Control', 'public, max-age=3600');
        res.writeHead(200);
        res.end(JSON.stringify(sim.fit.getJWKS()));
        return;
      }
      next();
    };
    const viteStack = (viteServer.middlewares as any).stack;
    if (Array.isArray(viteStack)) {
      viteStack.unshift({ route: '', handle: forgeMiddleware });
    } else {
      viteServer.middlewares.use(forgeMiddleware);
    }

    // 8c. Serve web trigger endpoints at /__trigger/<key>
    if (manifest.webTriggers.length > 0) {
      const webTriggerHandler = createWebTriggerHandler({ triggers: manifest.webTriggers, simulator: sim });
      const triggerMiddleware = (req: any, res: any, next: any) => {
        const url = new URL(req.url ?? '/', 'http://localhost');
        if (url.pathname.startsWith('/__trigger/')) {
          webTriggerHandler(req, res, url.pathname).catch((err: any) => {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: err.message }));
          });
          return;
        }
        next();
      };
      const triggerStack = (viteServer.middlewares as any).stack;
      if (Array.isArray(triggerStack)) {
        triggerStack.unshift({ route: '', handle: triggerMiddleware });
      } else {
        viteServer.middlewares.use(triggerMiddleware);
      }
      (globalThis as any).__forgeSim_devPort__ = port;
    }

    console.log(`     ➜ Tools:   ${localUrl}__tools/`);
    if (manifest.webTriggers.length > 0) {
      for (const wt of manifest.webTriggers) {
        console.log(`     ➜ Trigger: ${localUrl}__trigger/${wt.key}`);
      }
    }
    console.log('');
    for (const mod of detectedModules) {
      console.log(`     ➜ ${mod.module.key}: ${localUrl}module/${mod.module.key}/`);
    }
    console.log('');
    console.log(`     🔧 Source maps enabled — debug in Chrome DevTools`);
    console.log(`     ♻️  HMR enabled — edits refresh automatically`);
    console.log('');
    console.log('  ─────────────────────────────────────────────');
    console.log('');

    // Open browser if requested
    if (open) {
      const { exec: execCmd } = await import('node:child_process');
      // Best-effort browser open — works on macOS, Linux, Windows
      const openCommand = process.platform === 'darwin'
        ? `open "${localUrl}"`
        : process.platform === 'win32'
          ? `start "${localUrl}"`
          : `xdg-open "${localUrl}" 2>/dev/null || true`;
      execCmd(openCommand);
    }

    // Graceful shutdown
    let cleaningUp = false;
    const cleanup = async () => {
      if (cleaningUp) return; // prevent double-fire
      cleaningUp = true;
      console.log('\n  🛑 Shutting down...');

      // Save state before teardown
      try {
        await saveState(sim, stateDir);
      } catch (err: any) {
        console.error(`  ⚠️  Failed to save state: ${err.message}`);
      }

      toolsServer.close();
      devServer.close();
      await viteServer.close();
      // Clean up temp dir
      try { rmSync(tempDir, { recursive: true, force: true }); } catch {}
      process.exit(0);
    };

    // Must prevent default SIGINT behavior so our async cleanup can finish
    process.on('SIGINT', () => { cleanup().catch(() => process.exit(1)); });
    process.on('SIGTERM', () => { cleanup().catch(() => process.exit(1)); });

  } catch (err: any) {
    console.error(`  ❌ Failed to start Vite: ${err.message}`);
    console.error('');
    console.error('  Make sure you have the required dependencies installed:');
    console.error('    npm install --save-dev vite @vitejs/plugin-react');
    console.error('');
    devServer.close();
    process.exit(1);
  }
}

// ── Resolver-Only Deploy ──────────────────────────────────────────────────

/**
 * Deploy only the resolver/function modules — skip loading UI resources.
 * UI resources will run in the browser via Vite, not in Node.
 */
/**
 * Detect if a handler function is a real @forge/resolver dispatch function.
 * The dispatch function is created by Resolver.getDefinitions() and has a
 * characteristic signature: async ({ call: { functionKey, payload }, context }, backendRuntimePayload)
 *
 * We detect it by inspecting the function source — no probing (which would
 * cause side effects by actually executing handler code).
 */
function detectResolverDispatch(handler: Function): boolean {
  const src = handler.toString();
  // Real @forge/resolver dispatch function has 2 params and destructures { call: { functionKey } }
  return handler.length === 2 && src.includes('functionKey') && src.includes('call');
}

/**
 * Register a real @forge/resolver dispatch function on the simulator.
 *
 * The dispatch function's signature is:
 *   async ({ call: { functionKey, payload }, context }, backendRuntimePayload) => result
 *
 * We register the manifest function key (e.g., 'uiResolver') as a direct handler,
 * AND install a fallback on the simulator's invoke so that any unknown key
 * (e.g., 'retrieveData') gets routed through the dispatch function.
 */
function registerDispatchFunction(sim: ForgeSimulator, fnKey: string, dispatchFn: Function): void {
  // Register the function key itself so it shows up in the handler map
  sim.resolver.define(fnKey, async (req: any) => {
    return dispatchFn(
      { call: { functionKey: fnKey, payload: req.payload }, context: req.context },
      {}
    );
  });

  // Install a fallback: for any invoke(key) that doesn't match a registered
  // resolver, try routing through this dispatch function.
  // This handles calls like invoke('retrieveData') where 'retrieveData' is
  // a definition inside the resolver, not a top-level manifest function key.
  const originalInvoke = sim.resolver.invoke.bind(sim.resolver);
  sim.resolver.invoke = async (functionKey: string, payload?: any) => {
    try {
      return await originalInvoke(functionKey, payload);
    } catch (err: any) {
      if (err?.message?.includes('No resolver defined')) {
        const context = {
          accountId: 'sim-user-001',
          cloudId: 'sim-cloud-001',
          siteUrl: 'https://sim-site.atlassian.net',
        };
        return dispatchFn(
          { call: { functionKey, payload: payload ?? {} }, context },
          {}
        );
      }
      throw err;
    }
  };
}

async function deployResolversOnly(
  sim: ForgeSimulator,
  appDir: string,
  manifest: ParsedManifest
): Promise<{ loadedFunctions: string[]; errors: Array<{ functionKey: string; error: string }> }> {
  const loadedFunctions: string[] = [];
  const errors: Array<{ functionKey: string; error: string }> = [];

  // Find which functions are UI resource entry points — we'll skip those
  const resourceFunctionKeys = new Set<string>();
  for (const mod of manifest.uiModules) {
    // UI modules don't directly reference a function key — they reference a resource.
    // The resolver function IS what we want to load.
    // So we load ALL functions (resolvers, triggers, consumers) but skip resource imports.
  }

  for (const [fnKey, fnDef] of manifest.functions) {
    try {
      const { fileStem, exportName } = parseHandlerString(fnDef.handler);
      const filePath = await resolveHandlerFile(appDir, fileStem);

      if (!filePath) {
        errors.push({
          functionKey: fnKey,
          error: `Could not find handler file for "${fnDef.handler}"`,
        });
        continue;
      }

      const { pathToFileURL } = await import('node:url');
      const fileUrl = pathToFileURL(filePath).href;
      const mod = await import(fileUrl + '?t=' + Date.now());

      const handler = mod[exportName] ?? mod.default?.[exportName];
      if (!handler) {
        errors.push({
          functionKey: fnKey,
          error: `No export "${exportName}" in "${filePath}"`,
        });
        continue;
      }

      // Register as resolver — handle both shim and real @forge/resolver formats.
      //
      // Our shim's getDefinitions() returns { key: handler } (an object).
      // The real @forge/resolver's getDefinitions() returns a dispatch function:
      //   async ({ call: { functionKey, payload }, context }) => result
      //
      // When we get a dispatch function, we wrap individual resolver names
      // so the simulator can invoke them by name (e.g., 'retrieveData').
      if (typeof handler === 'object' && handler !== null) {
        // Shim format: { retrieveData: fn, otherKey: fn, ... }
        for (const [defKey, defHandler] of Object.entries(handler)) {
          if (typeof defHandler === 'function') {
            sim.resolver.define(defKey, defHandler as any);
          }
        }
      } else if (typeof handler === 'function') {
        // Could be the real @forge/resolver dispatch function, or a plain handler.
        // Try to detect by probing: call with a known-bad key and see if we get
        // the characteristic "Resolver has no definition" error.
        const isDispatchFn = detectResolverDispatch(handler);
        if (isDispatchFn) {
          // Real @forge/resolver — register a wrapper for this function key.
          // The UI calls invoke(definitionKey, payload), so we create a
          // pass-through that adapts our format to the dispatch function's format.
          registerDispatchFunction(sim, fnKey, handler);
        } else {
          // Plain function handler (trigger, consumer, etc.)
          sim.resolver.define(fnKey, handler);
        }
      }

      loadedFunctions.push(fnKey);
    } catch (err: any) {
      errors.push({
        functionKey: fnKey,
        error: err.message,
      });
    }
  }

  // Register manifest data FIRST — module routing, remotes, endpoints
  // This must happen before anything that might fail (FIT, scheduled triggers)
  sim.loadManifestData(manifest);

  // Initialize FIT provider if manifest has remotes (non-fatal)
  if (manifest.remotes.size > 0) {
    try {
      await sim.fit.init(appDir);
    } catch (err: any) {
      console.error(`  ⚠️  FIT initialization failed: ${err.message}`);
      console.error(`     Remote requests will be sent without authorization headers.`);
    }
  }

  // Wire up consumers
  for (const consumer of manifest.consumers) {
    const handlerMap = sim.resolver.getHandlerMap();
    const handler = handlerMap.get(consumer.functionKey);
    if (handler) {
      sim.registerConsumer(consumer.queue, handler as any);
    }
  }

  // Fire scheduled triggers once on deploy (e.g. migrations)
  for (const st of manifest.scheduledTriggers) {
    const handlerMap = sim.resolver.getHandlerMap();
    const handler = handlerMap.get(st.functionKey);
    if (handler && typeof handler === 'function') {
      try {
        console.log(` ⏰ Firing scheduled trigger: ${st.key} (${st.functionKey})`);
        await (handler as Function)({ scheduledTrigger: { key: st.key, interval: st.interval } });
      } catch (err: any) {
        console.error(` ⚠️ Scheduled trigger "${st.key}" failed:`, err.message);
        errors.push({ functionKey: st.functionKey, error: `Scheduled trigger error: ${err.message}` });
      }
    }
  }

  // Note: sim.loadManifestData(manifest) is called at the TOP of this function
  // to ensure module routing is always registered, even if later steps fail.
  return { loadedFunctions, errors };
}

// ── Helpers (duplicated from deployer to avoid side effects) ────────────

function parseHandlerString(handler: string): { fileStem: string; exportName: string } {
  const lastDot = handler.lastIndexOf('.');
  if (lastDot === -1) return { fileStem: handler, exportName: 'default' };
  return {
    fileStem: handler.substring(0, lastDot),
    exportName: handler.substring(lastDot + 1),
  };
}

const FILE_EXTENSIONS = ['.js', '.ts', '.tsx', '.jsx', '.mjs', '.cjs'];

async function resolveHandlerFile(appDir: string, fileStem: string): Promise<string | null> {
  const { access } = await import('node:fs/promises');

  // Try appDir-relative first (handles "src/resolver" → appDir/src/resolver.ts)
  for (const ext of FILE_EXTENSIONS) {
    const candidate = resolve(appDir, fileStem + ext);
    try { await access(candidate); return candidate; } catch {}
  }
  // Fallback: try under src/ (handles "resolver" → appDir/src/resolver.ts)
  for (const ext of FILE_EXTENSIONS) {
    const candidate = resolve(appDir, 'src', fileStem + ext);
    try { await access(candidate); return candidate; } catch {}
  }
  return null;
}
