/**
 * `forge-sim dev` command — the one-command Forge development experience.
 *
 * Reads manifest.yml, detects UIKit vs Custom UI, boots the simulator,
 * starts a WebSocket bridge for RPC, and launches Vite with the renderer.
 *
 * UIKit flow:
 *   1. Dev's @forge/react app code runs in browser (CDT debuggable)
 *   2. @forge/react reconciler produces ForgeDoc via bridge
 *   3. Bridge shim keeps ForgeDoc local (no server round-trip for renders)
 *   4. ForgeDocRenderer maps ForgeDoc → real Atlaskit components
 *   5. Backend calls (invoke, requestJira, etc.) route via WebSocket to simulator
 *
 * Custom UI flow:
 *   1. Dev's React app renders to DOM directly (it's a normal web app)
 *   2. @forge/bridge aliased to our shim
 *   3. Backend calls route via WebSocket to simulator
 *   4. No ForgeDoc, no Atlaskit mapping needed
 */

import { resolve, join, relative, dirname } from 'node:path';
import { existsSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ForgeSimulator } from './simulator.js';
import { deploy } from './deployer.js';
import { createDevServer } from './dev-server.js';
import { parseManifest, type ParsedManifest, type ManifestUIModule } from './manifest.js';
import { saveState, loadState, hasPersistedState, getSQLDumpPath } from './persistence.js';
import { buildDefaultContext } from './context.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface DevCommandOptions {
  appDir: string;
  port: number;
  wsPort: number;
  open: boolean;
  moduleKey?: string;
  /** Start fresh — don't restore persisted state */
  clean?: boolean;
}

// ── UI Module Detection ──────────────────────────────────────────────────

interface DetectedModule {
  module: ManifestUIModule;
  resourcePath: string;
  mode: 'uikit' | 'customui';
}

/**
 * Detect whether a UI module uses UIKit or Custom UI.
 *
 * UIKit modules:
 *   - Have a resource that points to a file importing @forge/react
 *   - The resource file calls ForgeReconciler.render()
 *
 * Custom UI modules:
 *   - Have a resource that points to a directory with index.html
 *   - Or a file that doesn't import @forge/react
 */
function detectModuleType(appDir: string, manifest: ParsedManifest, mod: ManifestUIModule): DetectedModule | null {
  if (!mod.resourceKey) {
    // No resource = server-only module (no UI to render)
    return null;
  }

  const resource = manifest.resources.get(mod.resourceKey);
  if (!resource) return null;

  const resourcePath = resolve(appDir, resource.path);

  // Check if it's a directory with index.html (Custom UI)
  if (existsSync(join(resourcePath, 'index.html'))) {
    return { module: mod, resourcePath, mode: 'customui' };
  }

  // Check if the resource points to a file
  const possibleFiles = [
    resourcePath,
    resourcePath + '.tsx',
    resourcePath + '.ts',
    resourcePath + '.jsx',
    resourcePath + '.js',
    join(resourcePath, 'index.tsx'),
    join(resourcePath, 'index.ts'),
    join(resourcePath, 'index.jsx'),
    join(resourcePath, 'index.js'),
  ];

  for (const filePath of possibleFiles) {
    if (existsSync(filePath)) {
      // Read file to check for @forge/react imports (UIKit indicator)
      try {
        const content = readFileSync(filePath, 'utf-8');
        if (content.includes('@forge/react') || content.includes('ForgeReconciler')) {
          return { module: mod, resourcePath: filePath, mode: 'uikit' };
        }
      } catch {}

      // If no @forge/react import, assume Custom UI
      return { module: mod, resourcePath: filePath, mode: 'customui' };
    }
  }

  return null;
}

// ── Entry Point Generation ────────────────────────────────────────────────

function generateUIKitEntry(appResourcePath: string, wsPort: number): string {
  return `
/**
 * Auto-generated by forge-sim dev
 * DO NOT EDIT — this file is regenerated on every run
 */

// Use dynamic imports to guarantee execution order:
// 1. Bridge shim installs globalThis.__bridge
// 2. Dev's app code runs (calls ForgeReconciler.render → produces ForgeDoc)
// 3. React DOM shell mounts (picks up ForgeDoc via onReconcile listener)

async function boot() {
  // 1. Install bridge shim — must happen before any @forge/react code
  const bridge = await import('forge-sim/renderer/bridge');
  bridge.configure({ wsUrl: 'ws://localhost:${wsPort}' });

  // 2. Import the developer's app — triggers ForgeReconciler.render()
  //    The bridge shim buffers the ForgeDoc so step 3 can pick it up
  await import('${appResourcePath}');

  // 3. Mount the Atlaskit renderer shell
  const React = await import('react');
  const ReactDOM = await import('react-dom/client');
  const { ForgeSimShell } = await import('forge-sim/renderer/ForgeSimShell');

  ReactDOM.createRoot(document.getElementById('root')!).render(
    React.createElement(React.StrictMode, null,
      React.createElement(ForgeSimShell)
    )
  );
}

boot().catch((err) => {
  console.error('[forge-sim] Boot failed:', err);
  document.getElementById('root')!.innerHTML =
    '<div style="padding:40px;font-family:monospace;color:#de350b">' +
    '<h2>⚠️ forge-sim failed to start</h2>' +
    '<pre>' + (err.stack || err.message || err) + '</pre></div>';
});
`;
}

function generateCustomUIEntry(_appResourcePath: string, wsPort: number): string {
  // For Custom UI, we generate a small bootstrap script that Vite injects.
  // The dev's index.html is served directly — this script just configures the bridge.
  return `
/**
 * Auto-generated by forge-sim dev (Custom UI mode)
 * Configures the @forge/bridge shim before the app loads.
 */
import { configure } from 'forge-sim/renderer/bridge-shim';
configure({ wsUrl: 'ws://localhost:${wsPort}' });
`;
}

function generateIndexHtml(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title} — forge-sim</title>
    <style>
      body { margin: 0; background: #f4f5f7; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./entry.tsx"></script>
  </body>
</html>`;
}

// ── Vite Config Builder ───────────────────────────────────────────────────

/**
 * Build the Vite config as a JS object — passed directly to createServer().
 * No config file needed, so Vite doesn't have to resolve 'vite' or plugin
 * imports from the app's directory.
 */
async function buildViteConfig(opts: {
  appDir: string;
  tempDir: string;
  resourceDir: string;
  mode: 'uikit' | 'customui';
  wsPort: number;
  port: number;
  forgeSimRoot: string;
}): Promise<any> {
  const { appDir, tempDir, resourceDir, mode, wsPort, port, forgeSimRoot } = opts;
  const shimPath = join(forgeSimRoot, 'renderer', 'src', 'bridge', 'forge-bridge-shim.ts');
  const bridgeBarrel = join(forgeSimRoot, 'renderer', 'src', 'bridge', 'index.ts');

  const rendererNodeModules = join(forgeSimRoot, 'renderer', 'node_modules');
  const mainNodeModules = join(forgeSimRoot, 'node_modules');
  const appNodeModules = join(appDir, 'node_modules');

  // Import the plugin directly — it's in forge-sim's node_modules
  const reactPlugin = (await import('@vitejs/plugin-react')).default;

  if (mode === 'customui') {
    // Custom UI: serve the resource directory directly.
    // The dev's index.html is the root — @forge/bridge is aliased to our shim.
    return {
      configFile: false as const,
      root: resourceDir,
      plugins: [reactPlugin()],
      server: {
        port,
        host: true,
        open: false,
        fs: {
          allow: [forgeSimRoot, appDir],
        },
      },
      resolve: {
        alias: {
          // @forge/bridge → our WebSocket shim (the FULL bridge shim, not the barrel)
          '@forge/bridge': shimPath,
          // For the bootstrap script import
          'forge-sim/renderer/bridge-shim': shimPath,
        },
        modules: [
          // Let the dev's custom UI find its own node_modules
          join(resourceDir, 'node_modules'),
          appNodeModules,
          rendererNodeModules,
          mainNodeModules,
          'node_modules',
        ],
      },
      define: {
        '__FORGE_SIM_WS_URL__': JSON.stringify(`ws://localhost:${wsPort}`),
      },
      // Custom UI apps may not use React at all — don't force it
      optimizeDeps: {
        exclude: [] as string[],
      },
    };
  }

  // UIKit: use the temp directory with generated entry point
  return {
    configFile: false as const,
    root: tempDir,
    plugins: [reactPlugin()],
    server: {
      port,
      host: true,
      open: false,
      fs: {
        allow: [forgeSimRoot, appDir],
      },
    },
    resolve: {
      alias: {
        '@forge/bridge': shimPath,
        'forge-sim/renderer/bridge': bridgeBarrel,
        'forge-sim/renderer/bridge-shim': shimPath,
        'forge-sim/renderer/ForgeDocRenderer': join(forgeSimRoot, 'renderer', 'src', 'ForgeDocRenderer.tsx'),
        'forge-sim/renderer/ForgeSimShell': join(forgeSimRoot, 'renderer', 'src', 'ForgeSimShell.tsx'),
      },
      modules: [
        rendererNodeModules,
        appNodeModules,
        mainNodeModules,
        'node_modules',
      ],
    },
    define: {
      '__FORGE_SIM_WS_URL__': JSON.stringify(`ws://localhost:${wsPort}`),
    },
    optimizeDeps: {
      include: ['react', 'react-dom', 'react/jsx-runtime'],
    },
  };
}

// ── Main Dev Command ──────────────────────────────────────────────────────

export async function devCommand(options: DevCommandOptions) {
  const { appDir, port, wsPort, open, moduleKey, clean } = options;
  const stateDir = join(appDir, '.forge-sim', 'state');

  console.log('');
  console.log('  🔥 forge-sim dev');
  console.log('  ─────────────────');
  console.log('');

  // 1. Validate app directory
  const manifestPath = join(appDir, 'manifest.yml');
  if (!existsSync(manifestPath)) {
    console.error(`  ❌ No manifest.yml found in ${appDir}`);
    console.error(`     Are you in a Forge app directory?`);
    process.exit(1);
  }

  // 2. Parse manifest
  console.log(`  📋 Reading manifest.yml...`);
  const manifest = await parseManifest(manifestPath);
  console.log(`     App: ${manifest.raw.app?.name ?? manifest.raw.app?.id ?? 'unnamed'}`);
  console.log(`     Functions: ${manifest.functions.size}`);
  console.log(`     UI modules: ${manifest.uiModules.length}`);
  console.log('');

  // 3. Find UI module to render
  const detectedModules: DetectedModule[] = [];
  for (const mod of manifest.uiModules) {
    if (moduleKey && mod.key !== moduleKey) continue;
    const detected = detectModuleType(appDir, manifest, mod);
    if (detected) detectedModules.push(detected);
  }

  if (detectedModules.length === 0) {
    console.error(`  ❌ No UI modules found${moduleKey ? ` with key "${moduleKey}"` : ''}`);
    console.error(`     Your manifest needs a module with a resource (jira:issuePanel, etc.)`);
    process.exit(1);
  }

  // Use the first detected module (or the one matching --module key)
  const target = moduleKey
    ? detectedModules.find((d) => d.module.key === moduleKey) ?? detectedModules[0]
    : detectedModules[0];

  const modeLabel = target.mode === 'uikit' ? 'UIKit 2' : 'Custom UI';
  console.log(`  🎯 Module: ${target.module.key} (${target.module.type})`);
  console.log(`  🖼️  Mode: ${modeLabel}`);
  console.log(`  📁 Resource: ${relative(appDir, target.resourcePath)}`);
  console.log('');

  if (detectedModules.length > 1) {
    console.log(`  ℹ️  Found ${detectedModules.length} UI modules. Using "${target.module.key}".`);
    console.log(`     Use --module <key> to pick a different one.`);
    console.log(`     Available: ${detectedModules.map((d) => d.module.key).join(', ')}`);
    console.log('');
  }

  // 4. Create simulator and deploy resolvers
  console.log(`  ⚙️  Starting simulator...`);
  const sim = new ForgeSimulator();

  // 4a. Configure SQL restore BEFORE deploy — deploy can trigger scheduled
  // triggers (migrations) which lazily start SQL. The init file must be set
  // before that happens so persisted tables exist when migrations check.
  if (!clean) {
    const sqlDumpPath = await getSQLDumpPath(stateDir);
    if (sqlDumpPath) {
      sim.sql.setInitSQLFilePath(sqlDumpPath);
      // Read table count for logging
      const { readFileSync } = await import('node:fs');
      const dump = readFileSync(sqlDumpPath, 'utf-8');
      const tableCount = (dump.match(/CREATE TABLE/gi) || []).length;
      console.log(`  📂 Restoring SQL state (${tableCount} tables) on MySQL boot`);
    }
  }

  // Set the global simulator instance so that @forge/* shims
  // (loaded via our module hooks) can register handlers directly
  const { setSimulator } = await import('./shims/globals.js');
  setSimulator(sim);

  // Deploy functions (resolvers, triggers, etc.) — these run on the server side
  // For browser mode, we skip loading UI resources (they'll run in the browser)
  try {
    console.log(`     Resolver before deploy: [${[...sim.resolver.getHandlerMap().keys()].join(', ')}]`);
    const deployResult = await deployResolversOnly(sim, appDir, manifest);
    console.log(`     Resolver after deploy: [${[...sim.resolver.getHandlerMap().keys()].join(', ')}]`);
    if (deployResult.loadedFunctions.length > 0) {
      console.log(`     Loaded ${deployResult.loadedFunctions.length} function(s): ${deployResult.loadedFunctions.join(', ')}`);
    }
    if (deployResult.errors.length > 0) {
      for (const err of deployResult.errors) {
        console.warn(`     ⚠️  ${err.functionKey}: ${err.error}`);
      }
    }
  } catch (err: any) {
    console.warn(`     ⚠️  Deploy warning: ${err.message}`);
  }

  // 4b. Restore KVS state (unless --clean)
  // (SQL restore already configured in 4a via initSQLFilePath)
  if (!clean) {
    if (await hasPersistedState(stateDir)) {
      await loadState(sim, stateDir);
    }
  }

  // 4c. Connect to real Atlassian APIs if credentials exist
  try {
    const { loadCredentials, getDefaultAccount, saveCredentials, upsertAccount } = await import('./auth/credentials.js');
    const store = await loadCredentials(appDir);
    const account = getDefaultAccount(store);

    if (account) {
      // Set up OAuth config for token refresh (only needed for OAuth accounts)
      if (account.authType === 'oauth') {
        try {
          const { getOAuthAppConfig } = await import('./auth/config.js');
          const { setOAuthConfig } = await import('./auth/oauth.js');
          const oauthAppConfig = await getOAuthAppConfig();
          if (oauthAppConfig) setOAuthConfig(oauthAppConfig);
        } catch {}
      }

      sim.productApi.connectRealApis(account, {
        onTokenRefresh: (refreshedAccount) => {
          upsertAccount(store, refreshedAccount);
          saveCredentials(store).catch(() => {});
        },
      });
    } else {
      console.log(`  📡 No Atlassian accounts — using mock APIs`);
      console.log(`     Run 'forge-sim auth' to connect to a real site`);
    }
  } catch (err: any) {
    console.log(`  📡 Using mock APIs (auth load failed: ${err.message})`);
  }

  console.log('');

  // 5. Start WebSocket dev server (for RPC: invoke, fetchProduct, etc.)
  console.log(`  🔌 Starting WebSocket bridge on port ${wsPort}...`);
  const devServer = createDevServer({
    port: wsPort,
    watchDir: join(appDir, 'src'),
    simulator: sim,
    context: buildDefaultContext(
      target.module.key,
      target.module.type,
      sim.productApi.connectedAccount,
    ),
  });

  // 6. Generate temp project for Vite
  const forgeSimRoot = resolve(__dirname, '..');
  const tempDir = join(appDir, '.forge-sim', 'tmp');

  // Clean up previous temp files (but preserve .forge-sim/state/)
  if (existsSync(tempDir)) {
    rmSync(tempDir, { recursive: true, force: true });
  }

  if (target.mode === 'uikit') {
    // UIKit: generate entry point and index.html in temp dir
    mkdirSync(tempDir, { recursive: true });

    const appResourceRelative = relative(tempDir, target.resourcePath).replace(/\\/g, '/');
    const appResourceImportPath = appResourceRelative.startsWith('.') ? appResourceRelative : './' + appResourceRelative;
    const entryContent = generateUIKitEntry(appResourceImportPath, wsPort);

    writeFileSync(join(tempDir, 'entry.tsx'), entryContent);
    writeFileSync(join(tempDir, 'index.html'), generateIndexHtml(manifest.raw.app?.name ?? 'Forge App'));
    // .gitignore at .forge-sim/ level covers both tmp/ and state/
    writeFileSync(join(appDir, '.forge-sim', '.gitignore'), '*\n');

    console.log(`  📦 Generated UIKit dev environment in .forge-sim/tmp/`);
  } else {
    // Custom UI: serve the resource directory directly.
    // Vite uses the dev's index.html as-is, @forge/bridge is aliased to our shim.
    console.log(`  📦 Custom UI — serving ${relative(appDir, target.resourcePath)}/ directly`);
  }
  console.log('');

  // 7. Start Vite
  console.log(`  🚀 Starting Vite dev server...`);
  console.log('');

  try {
    const { createServer } = await import('vite');

    const viteConfig = await buildViteConfig({
      appDir,
      tempDir,
      resourceDir: target.resourcePath,
      mode: target.mode,
      wsPort,
      port,
      forgeSimRoot,
    });

    const viteServer = await createServer(viteConfig);

    await viteServer.listen();

    const info = viteServer.resolvedUrls;
    const localUrl = info?.local?.[0] ?? `http://localhost:${port}`;
    const networkUrl = info?.network?.[0];

    console.log('  ─────────────────────────────────────────────');
    console.log('');
    console.log(`  🔥 forge-sim dev server running!`);
    console.log('');
    console.log(`     ${modeLabel} mode • ${target.module.type}:${target.module.key}`);
    console.log('');
    console.log(`     ➜ Local:   ${localUrl}`);
    if (networkUrl) {
      console.log(`     ➜ Network: ${networkUrl}`);
    }
    console.log(`     ➜ WS:      ws://localhost:${wsPort}`);

    // 8. Start Forge Sim Tools (uses Vite's HTTP server via middleware)
    const { attachToolsToVite } = await import('./tools/server.js');
    const toolsServer = attachToolsToVite({ sim, manifest, viteServer, appDir });

    // Hook simulator logs into tools broadcast
    sim.onLog((entry: any) => {
      toolsServer.broadcastLog(entry);
    });

    console.log(`     ➜ Tools:   ${localUrl}__tools/`);
    console.log('');
    console.log(`     ${target.mode === 'uikit' ? '🎨 Rendering with real Atlaskit components' : '🖥️  Custom UI — your app renders directly'}`);
    console.log(`     🔧 Source maps enabled — debug in Chrome DevTools`);
    console.log(`     ♻️  HMR enabled — edits refresh automatically`);
    console.log('');
    console.log('  ─────────────────────────────────────────────');
    console.log('');

    // Open browser if requested
    if (open) {
      const { exec: execCmd } = await import('node:child_process');
      // Best-effort browser open — works on macOS, Linux, Windows
      const openCommand = process.platform === 'darwin'
        ? `open "${localUrl}"`
        : process.platform === 'win32'
          ? `start "${localUrl}"`
          : `xdg-open "${localUrl}" 2>/dev/null || true`;
      execCmd(openCommand);
    }

    // Graceful shutdown
    let cleaningUp = false;
    const cleanup = async () => {
      if (cleaningUp) return; // prevent double-fire
      cleaningUp = true;
      console.log('\n  🛑 Shutting down...');

      // Save state before teardown
      try {
        await saveState(sim, stateDir);
      } catch (err: any) {
        console.error(`  ⚠️  Failed to save state: ${err.message}`);
      }

      toolsServer.close();
      devServer.close();
      await viteServer.close();
      // Clean up temp dir
      try { rmSync(tempDir, { recursive: true, force: true }); } catch {}
      process.exit(0);
    };

    // Must prevent default SIGINT behavior so our async cleanup can finish
    process.on('SIGINT', () => { cleanup().catch(() => process.exit(1)); });
    process.on('SIGTERM', () => { cleanup().catch(() => process.exit(1)); });

  } catch (err: any) {
    console.error(`  ❌ Failed to start Vite: ${err.message}`);
    console.error('');
    console.error('  Make sure you have the required dependencies installed:');
    console.error('    npm install --save-dev vite @vitejs/plugin-react');
    console.error('');
    devServer.close();
    process.exit(1);
  }
}

// ── Resolver-Only Deploy ──────────────────────────────────────────────────

/**
 * Deploy only the resolver/function modules — skip loading UI resources.
 * UI resources will run in the browser via Vite, not in Node.
 */
/**
 * Detect if a handler function is a real @forge/resolver dispatch function.
 * The dispatch function is created by Resolver.getDefinitions() and has a
 * characteristic signature: async ({ call: { functionKey, payload }, context }, backendRuntimePayload)
 *
 * We detect it by inspecting the function source — no probing (which would
 * cause side effects by actually executing handler code).
 */
function detectResolverDispatch(handler: Function): boolean {
  const src = handler.toString();
  // Real @forge/resolver dispatch function has 2 params and destructures { call: { functionKey } }
  return handler.length === 2 && src.includes('functionKey') && src.includes('call');
}

/**
 * Register a real @forge/resolver dispatch function on the simulator.
 *
 * The dispatch function's signature is:
 *   async ({ call: { functionKey, payload }, context }, backendRuntimePayload) => result
 *
 * We register the manifest function key (e.g., 'uiResolver') as a direct handler,
 * AND install a fallback on the simulator's invoke so that any unknown key
 * (e.g., 'retrieveData') gets routed through the dispatch function.
 */
function registerDispatchFunction(sim: ForgeSimulator, fnKey: string, dispatchFn: Function): void {
  // Register the function key itself so it shows up in the handler map
  sim.resolver.define(fnKey, async (req: any) => {
    return dispatchFn(
      { call: { functionKey: fnKey, payload: req.payload }, context: req.context },
      {}
    );
  });

  // Install a fallback: for any invoke(key) that doesn't match a registered
  // resolver, try routing through this dispatch function.
  // This handles calls like invoke('retrieveData') where 'retrieveData' is
  // a definition inside the resolver, not a top-level manifest function key.
  const originalInvoke = sim.resolver.invoke.bind(sim.resolver);
  sim.resolver.invoke = async (functionKey: string, payload?: any) => {
    try {
      return await originalInvoke(functionKey, payload);
    } catch (err: any) {
      if (err?.message?.includes('No resolver defined')) {
        const context = {
          accountId: 'sim-user-001',
          cloudId: 'sim-cloud-001',
          siteUrl: 'https://sim-site.atlassian.net',
        };
        return dispatchFn(
          { call: { functionKey, payload: payload ?? {} }, context },
          {}
        );
      }
      throw err;
    }
  };
}

async function deployResolversOnly(
  sim: ForgeSimulator,
  appDir: string,
  manifest: ParsedManifest
): Promise<{ loadedFunctions: string[]; errors: Array<{ functionKey: string; error: string }> }> {
  const loadedFunctions: string[] = [];
  const errors: Array<{ functionKey: string; error: string }> = [];

  // Find which functions are UI resource entry points — we'll skip those
  const resourceFunctionKeys = new Set<string>();
  for (const mod of manifest.uiModules) {
    // UI modules don't directly reference a function key — they reference a resource.
    // The resolver function IS what we want to load.
    // So we load ALL functions (resolvers, triggers, consumers) but skip resource imports.
  }

  for (const [fnKey, fnDef] of manifest.functions) {
    try {
      const { fileStem, exportName } = parseHandlerString(fnDef.handler);
      const filePath = await resolveHandlerFile(appDir, fileStem);

      if (!filePath) {
        errors.push({
          functionKey: fnKey,
          error: `Could not find handler file for "${fnDef.handler}"`,
        });
        continue;
      }

      const { pathToFileURL } = await import('node:url');
      const fileUrl = pathToFileURL(filePath).href;
      const mod = await import(fileUrl + '?t=' + Date.now());

      const handler = mod[exportName] ?? mod.default?.[exportName];
      if (!handler) {
        errors.push({
          functionKey: fnKey,
          error: `No export "${exportName}" in "${filePath}"`,
        });
        continue;
      }

      // Register as resolver — handle both shim and real @forge/resolver formats.
      //
      // Our shim's getDefinitions() returns { key: handler } (an object).
      // The real @forge/resolver's getDefinitions() returns a dispatch function:
      //   async ({ call: { functionKey, payload }, context }) => result
      //
      // When we get a dispatch function, we wrap individual resolver names
      // so the simulator can invoke them by name (e.g., 'retrieveData').
      if (typeof handler === 'object' && handler !== null) {
        // Shim format: { retrieveData: fn, otherKey: fn, ... }
        for (const [defKey, defHandler] of Object.entries(handler)) {
          if (typeof defHandler === 'function') {
            sim.resolver.define(defKey, defHandler as any);
          }
        }
      } else if (typeof handler === 'function') {
        // Could be the real @forge/resolver dispatch function, or a plain handler.
        // Try to detect by probing: call with a known-bad key and see if we get
        // the characteristic "Resolver has no definition" error.
        const isDispatchFn = detectResolverDispatch(handler);
        if (isDispatchFn) {
          // Real @forge/resolver — register a wrapper for this function key.
          // The UI calls invoke(definitionKey, payload), so we create a
          // pass-through that adapts our format to the dispatch function's format.
          registerDispatchFunction(sim, fnKey, handler);
        } else {
          // Plain function handler (trigger, consumer, etc.)
          sim.resolver.define(fnKey, handler);
        }
      }

      loadedFunctions.push(fnKey);
    } catch (err: any) {
      errors.push({
        functionKey: fnKey,
        error: err.message,
      });
    }
  }

  // Wire up consumers
  for (const consumer of manifest.consumers) {
    const handlerMap = sim.resolver.getHandlerMap();
    const handler = handlerMap.get(consumer.functionKey);
    if (handler) {
      sim.registerConsumer(consumer.queue, handler as any);
    }
  }

  // Fire scheduled triggers once on deploy (e.g. migrations)
  for (const st of manifest.scheduledTriggers) {
    const handlerMap = sim.resolver.getHandlerMap();
    const handler = handlerMap.get(st.functionKey);
    if (handler && typeof handler === 'function') {
      try {
        console.log(` ⏰ Firing scheduled trigger: ${st.key} (${st.functionKey})`);
        await (handler as Function)({ scheduledTrigger: { key: st.key, interval: st.interval } });
      } catch (err: any) {
        console.error(` ⚠️ Scheduled trigger "${st.key}" failed:`, err.message);
        errors.push({ functionKey: st.functionKey, error: `Scheduled trigger error: ${err.message}` });
      }
    }
  }

  sim.loadManifestData(manifest);
  return { loadedFunctions, errors };
}

// ── Helpers (duplicated from deployer to avoid side effects) ────────────

function parseHandlerString(handler: string): { fileStem: string; exportName: string } {
  const lastDot = handler.lastIndexOf('.');
  if (lastDot === -1) return { fileStem: handler, exportName: 'default' };
  return {
    fileStem: handler.substring(0, lastDot),
    exportName: handler.substring(lastDot + 1),
  };
}

const FILE_EXTENSIONS = ['.js', '.ts', '.tsx', '.jsx', '.mjs', '.cjs'];

async function resolveHandlerFile(appDir: string, fileStem: string): Promise<string | null> {
  const { access } = await import('node:fs/promises');

  // Try appDir-relative first (handles "src/resolver" → appDir/src/resolver.ts)
  for (const ext of FILE_EXTENSIONS) {
    const candidate = resolve(appDir, fileStem + ext);
    try { await access(candidate); return candidate; } catch {}
  }
  // Fallback: try under src/ (handles "resolver" → appDir/src/resolver.ts)
  for (const ext of FILE_EXTENSIONS) {
    const candidate = resolve(appDir, 'src', fileStem + ext);
    try { await access(candidate); return candidate; } catch {}
  }
  return null;
}
