/**
 * `forge-sim dev` command — the one-command Forge development experience.
 *
 * Reads manifest.yml, detects UIKit vs Custom UI, boots the simulator,
 * starts a WebSocket bridge for RPC, and launches Vite with the renderer.
 *
 * UIKit flow:
 *   1. Dev's @forge/react app code runs in browser (CDT debuggable)
 *   2. @forge/react reconciler produces ForgeDoc via bridge
 *   3. Bridge shim keeps ForgeDoc local (no server round-trip for renders)
 *   4. ForgeDocRenderer maps ForgeDoc → real Atlaskit components
 *   5. Backend calls (invoke, requestJira, etc.) route via WebSocket to simulator
 *
 * Custom UI flow:
 *   1. Dev's React app renders to DOM directly (it's a normal web app)
 *   2. @forge/bridge aliased to our shim
 *   3. Backend calls route via WebSocket to simulator
 *   4. No ForgeDoc, no Atlaskit mapping needed
 */

import { resolve, join, relative, dirname } from 'node:path';
import { existsSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ForgeSimulator } from './simulator.js';
import { deploy } from './deployer.js';
import { createDevServer } from './dev-server.js';
import { parseManifest, type ParsedManifest, type ManifestUIModule } from './manifest.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface DevCommandOptions {
  appDir: string;
  port: number;
  wsPort: number;
  open: boolean;
  moduleKey?: string;
}

// ── UI Module Detection ──────────────────────────────────────────────────

interface DetectedModule {
  module: ManifestUIModule;
  resourcePath: string;
  mode: 'uikit' | 'customui';
}

/**
 * Detect whether a UI module uses UIKit or Custom UI.
 *
 * UIKit modules:
 *   - Have a resource that points to a file importing @forge/react
 *   - The resource file calls ForgeReconciler.render()
 *
 * Custom UI modules:
 *   - Have a resource that points to a directory with index.html
 *   - Or a file that doesn't import @forge/react
 */
function detectModuleType(appDir: string, manifest: ParsedManifest, mod: ManifestUIModule): DetectedModule | null {
  if (!mod.resourceKey) {
    // No resource = server-only module (no UI to render)
    return null;
  }

  const resource = manifest.resources.get(mod.resourceKey);
  if (!resource) return null;

  const resourcePath = resolve(appDir, resource.path);

  // Check if it's a directory with index.html (Custom UI)
  if (existsSync(join(resourcePath, 'index.html'))) {
    return { module: mod, resourcePath, mode: 'customui' };
  }

  // Check if the resource points to a file
  const possibleFiles = [
    resourcePath,
    resourcePath + '.tsx',
    resourcePath + '.ts',
    resourcePath + '.jsx',
    resourcePath + '.js',
    join(resourcePath, 'index.tsx'),
    join(resourcePath, 'index.ts'),
    join(resourcePath, 'index.jsx'),
    join(resourcePath, 'index.js'),
  ];

  for (const filePath of possibleFiles) {
    if (existsSync(filePath)) {
      // Read file to check for @forge/react imports (UIKit indicator)
      try {
        const content = readFileSync(filePath, 'utf-8');
        if (content.includes('@forge/react') || content.includes('ForgeReconciler')) {
          return { module: mod, resourcePath: filePath, mode: 'uikit' };
        }
      } catch {}

      // If no @forge/react import, assume Custom UI
      return { module: mod, resourcePath: filePath, mode: 'customui' };
    }
  }

  return null;
}

// ── Entry Point Generation ────────────────────────────────────────────────

function generateUIKitEntry(appResourcePath: string, wsPort: number): string {
  return `
/**
 * Auto-generated by forge-sim dev
 * DO NOT EDIT — this file is regenerated on every run
 */

// Use dynamic imports to guarantee execution order:
// 1. Bridge shim installs globalThis.__bridge
// 2. Dev's app code runs (calls ForgeReconciler.render → produces ForgeDoc)
// 3. React DOM shell mounts (picks up ForgeDoc via onReconcile listener)

async function boot() {
  // 1. Install bridge shim — must happen before any @forge/react code
  const bridge = await import('forge-sim/renderer/bridge');
  bridge.configure({ wsUrl: 'ws://localhost:${wsPort}' });

  // 2. Import the developer's app — triggers ForgeReconciler.render()
  //    The bridge shim buffers the ForgeDoc so step 3 can pick it up
  await import('${appResourcePath}');

  // 3. Mount the Atlaskit renderer shell
  const React = await import('react');
  const ReactDOM = await import('react-dom/client');
  const { ForgeSimShell } = await import('forge-sim/renderer/ForgeSimShell');

  ReactDOM.createRoot(document.getElementById('root')!).render(
    React.createElement(React.StrictMode, null,
      React.createElement(ForgeSimShell)
    )
  );
}

boot().catch((err) => {
  console.error('[forge-sim] Boot failed:', err);
  document.getElementById('root')!.innerHTML =
    '<div style="padding:40px;font-family:monospace;color:#de350b">' +
    '<h2>⚠️ forge-sim failed to start</h2>' +
    '<pre>' + (err.stack || err.message || err) + '</pre></div>';
});
`;
}

function generateCustomUIEntry(appResourcePath: string, wsPort: number): string {
  return `
/**
 * Auto-generated by forge-sim dev (Custom UI mode)
 * DO NOT EDIT — this file is regenerated on every run
 *
 * Your app renders directly to DOM. @forge/bridge calls are
 * routed to forge-sim's backend via WebSocket.
 */

// Install the bridge shim so @forge/bridge imports resolve to our WebSocket shim
import { configure } from 'forge-sim/renderer/bridge';
configure({ wsUrl: 'ws://localhost:${wsPort}' });

// Import and run the developer's app
import '${appResourcePath}';
`;
}

function generateIndexHtml(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title} — forge-sim</title>
    <style>
      body { margin: 0; background: #f4f5f7; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./entry.tsx"></script>
  </body>
</html>`;
}

// ── Vite Config Generation ────────────────────────────────────────────────

function generateViteConfig(opts: {
  appDir: string;
  mode: 'uikit' | 'customui';
  wsPort: number;
  port: number;
  forgeSimRoot: string;
}): string {
  const { appDir, mode, wsPort, port, forgeSimRoot } = opts;
  // Path to the bridge shim source file
  const shimPath = join(forgeSimRoot, 'renderer', 'src', 'bridge', 'forge-bridge-shim.ts');

  // Renderer's node_modules has all the Atlaskit packages
  const rendererNodeModules = join(forgeSimRoot, 'renderer', 'node_modules');
  const mainNodeModules = join(forgeSimRoot, 'node_modules');
  // App's node_modules for @forge/react, @forge/bridge, etc.
  const appNodeModules = join(appDir, 'node_modules');

  return `
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: ${port},
    host: true,
    open: false,
    fs: {
      // Allow Vite to serve files from outside the project root
      allow: ['${forgeSimRoot.replace(/\\/g, '/')}', '${appDir.replace(/\\/g, '/')}'],
    },
  },
  resolve: {
    alias: {
      // Route @forge/bridge imports to our WebSocket bridge shim
      '@forge/bridge': '${shimPath.replace(/\\/g, '/')}',
      // Allow importing from forge-sim package
      'forge-sim/renderer/bridge': '${join(forgeSimRoot, 'renderer', 'src', 'bridge', 'index.ts').replace(/\\/g, '/')}',
      'forge-sim/renderer/ForgeDocRenderer': '${join(forgeSimRoot, 'renderer', 'src', 'ForgeDocRenderer.tsx').replace(/\\/g, '/')}',
      'forge-sim/renderer/ForgeSimShell': '${join(forgeSimRoot, 'renderer', 'src', 'ForgeSimShell.tsx').replace(/\\/g, '/')}',
    },
    // Tell Vite where to find node_modules — renderer has Atlaskit, app has @forge/*
    modules: [
      '${rendererNodeModules.replace(/\\/g, '/')}',
      '${appNodeModules.replace(/\\/g, '/')}',
      '${mainNodeModules.replace(/\\/g, '/')}',
      'node_modules',
    ],
  },
  define: {
    '__FORGE_SIM_WS_URL__': JSON.stringify('ws://localhost:${wsPort}'),
  },
  optimizeDeps: {
    include: ['react', 'react-dom', 'react/jsx-runtime'],
  },
});
`;
}

// ── Main Dev Command ──────────────────────────────────────────────────────

export async function devCommand(options: DevCommandOptions) {
  const { appDir, port, wsPort, open, moduleKey } = options;

  console.log('');
  console.log('  🔥 forge-sim dev');
  console.log('  ─────────────────');
  console.log('');

  // 1. Validate app directory
  const manifestPath = join(appDir, 'manifest.yml');
  if (!existsSync(manifestPath)) {
    console.error(`  ❌ No manifest.yml found in ${appDir}`);
    console.error(`     Are you in a Forge app directory?`);
    process.exit(1);
  }

  // 2. Parse manifest
  console.log(`  📋 Reading manifest.yml...`);
  const manifest = await parseManifest(manifestPath);
  console.log(`     App: ${manifest.raw.app?.name ?? manifest.raw.app?.id ?? 'unnamed'}`);
  console.log(`     Functions: ${manifest.functions.size}`);
  console.log(`     UI modules: ${manifest.uiModules.length}`);
  console.log('');

  // 3. Find UI module to render
  const detectedModules: DetectedModule[] = [];
  for (const mod of manifest.uiModules) {
    if (moduleKey && mod.key !== moduleKey) continue;
    const detected = detectModuleType(appDir, manifest, mod);
    if (detected) detectedModules.push(detected);
  }

  if (detectedModules.length === 0) {
    console.error(`  ❌ No UI modules found${moduleKey ? ` with key "${moduleKey}"` : ''}`);
    console.error(`     Your manifest needs a module with a resource (jira:issuePanel, etc.)`);
    process.exit(1);
  }

  // Use the first detected module (or the one matching --module key)
  const target = moduleKey
    ? detectedModules.find((d) => d.module.key === moduleKey) ?? detectedModules[0]
    : detectedModules[0];

  const modeLabel = target.mode === 'uikit' ? 'UIKit 2' : 'Custom UI';
  console.log(`  🎯 Module: ${target.module.key} (${target.module.type})`);
  console.log(`  🖼️  Mode: ${modeLabel}`);
  console.log(`  📁 Resource: ${relative(appDir, target.resourcePath)}`);
  console.log('');

  if (detectedModules.length > 1) {
    console.log(`  ℹ️  Found ${detectedModules.length} UI modules. Using "${target.module.key}".`);
    console.log(`     Use --module <key> to pick a different one.`);
    console.log(`     Available: ${detectedModules.map((d) => d.module.key).join(', ')}`);
    console.log('');
  }

  // 4. Create simulator and deploy resolvers
  console.log(`  ⚙️  Starting simulator...`);
  const sim = new ForgeSimulator();

  // Deploy functions (resolvers, triggers, etc.) — these run on the server side
  // For browser mode, we skip loading UI resources (they'll run in the browser)
  try {
    const deployResult = await deployResolversOnly(sim, appDir, manifest);
    if (deployResult.loadedFunctions.length > 0) {
      console.log(`     Loaded ${deployResult.loadedFunctions.length} function(s): ${deployResult.loadedFunctions.join(', ')}`);
    }
    if (deployResult.errors.length > 0) {
      for (const err of deployResult.errors) {
        console.warn(`     ⚠️  ${err.functionKey}: ${err.error}`);
      }
    }
  } catch (err: any) {
    console.warn(`     ⚠️  Deploy warning: ${err.message}`);
  }
  console.log('');

  // 5. Start WebSocket dev server (for RPC: invoke, fetchProduct, etc.)
  console.log(`  🔌 Starting WebSocket bridge on port ${wsPort}...`);
  const devServer = createDevServer({
    port: wsPort,
    watchDir: join(appDir, 'src'),
    simulator: sim,
    context: {
      accountId: 'sim-user-001',
      cloudId: 'sim-cloud-001',
      siteUrl: 'https://sim-site.atlassian.net',
      moduleKey: target.module.key,
      environmentId: 'sim-env',
      environmentType: 'DEVELOPMENT',
      localId: `forge-sim-${Date.now()}`,
      locale: 'en-US',
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      extension: {
        type: target.module.type,
      },
    },
  });

  // 6. Generate temp project for Vite
  const forgeSimRoot = resolve(__dirname, '..');
  const tempDir = join(appDir, '.forge-sim');

  // Clean up any previous temp dir
  if (existsSync(tempDir)) {
    rmSync(tempDir, { recursive: true, force: true });
  }
  mkdirSync(tempDir, { recursive: true });

  // Generate entry point
  const appResourceRelative = relative(tempDir, target.resourcePath).replace(/\\/g, '/');
  // Ensure the relative path starts with ./ for Vite
  const appResourceImportPath = appResourceRelative.startsWith('.') ? appResourceRelative : './' + appResourceRelative;

  const entryContent = target.mode === 'uikit'
    ? generateUIKitEntry(appResourceImportPath, wsPort)
    : generateCustomUIEntry(appResourceImportPath, wsPort);

  writeFileSync(join(tempDir, 'entry.tsx'), entryContent);
  writeFileSync(join(tempDir, 'index.html'), generateIndexHtml(manifest.raw.app?.name ?? 'Forge App'));
  writeFileSync(join(tempDir, 'vite.config.ts'), generateViteConfig({
    appDir,
    mode: target.mode,
    wsPort,
    port,
    forgeSimRoot,
  }));

  // Add .gitignore so the temp dir doesn't get committed
  writeFileSync(join(tempDir, '.gitignore'), '*\n');

  console.log(`  📦 Generated dev environment in .forge-sim/`);
  console.log('');

  // 7. Start Vite
  console.log(`  🚀 Starting Vite dev server...`);
  console.log('');

  try {
    const { createServer } = await import('vite');

    const viteServer = await createServer({
      configFile: join(tempDir, 'vite.config.ts'),
      root: tempDir,
    });

    await viteServer.listen();

    const info = viteServer.resolvedUrls;
    const localUrl = info?.local?.[0] ?? `http://localhost:${port}`;
    const networkUrl = info?.network?.[0];

    console.log('  ─────────────────────────────────────────────');
    console.log('');
    console.log(`  🔥 forge-sim dev server running!`);
    console.log('');
    console.log(`     ${modeLabel} mode • ${target.module.type}:${target.module.key}`);
    console.log('');
    console.log(`     ➜ Local:   ${localUrl}`);
    if (networkUrl) {
      console.log(`     ➜ Network: ${networkUrl}`);
    }
    console.log(`     ➜ WS:      ws://localhost:${wsPort}`);
    console.log('');
    console.log(`     ${target.mode === 'uikit' ? '🎨 Rendering with real Atlaskit components' : '🖥️  Custom UI — your app renders directly'}`);
    console.log(`     🔧 Source maps enabled — debug in Chrome DevTools`);
    console.log(`     ♻️  HMR enabled — edits refresh automatically`);
    console.log('');
    console.log('  ─────────────────────────────────────────────');
    console.log('');

    // Open browser if requested
    if (open) {
      const { exec: execCmd } = await import('node:child_process');
      // Best-effort browser open — works on macOS, Linux, Windows
      const openCommand = process.platform === 'darwin'
        ? `open "${localUrl}"`
        : process.platform === 'win32'
          ? `start "${localUrl}"`
          : `xdg-open "${localUrl}" 2>/dev/null || true`;
      execCmd(openCommand);
    }

    // Graceful shutdown
    const cleanup = async () => {
      console.log('\n  🛑 Shutting down...');
      devServer.close();
      await viteServer.close();
      // Clean up temp dir
      try { rmSync(tempDir, { recursive: true, force: true }); } catch {}
      process.exit(0);
    };

    process.on('SIGINT', cleanup);
    process.on('SIGTERM', cleanup);

  } catch (err: any) {
    console.error(`  ❌ Failed to start Vite: ${err.message}`);
    console.error('');
    console.error('  Make sure you have the required dependencies installed:');
    console.error('    npm install --save-dev vite @vitejs/plugin-react');
    console.error('');
    devServer.close();
    process.exit(1);
  }
}

// ── Resolver-Only Deploy ──────────────────────────────────────────────────

/**
 * Deploy only the resolver/function modules — skip loading UI resources.
 * UI resources will run in the browser via Vite, not in Node.
 */
async function deployResolversOnly(
  sim: ForgeSimulator,
  appDir: string,
  manifest: ParsedManifest
): Promise<{ loadedFunctions: string[]; errors: Array<{ functionKey: string; error: string }> }> {
  const loadedFunctions: string[] = [];
  const errors: Array<{ functionKey: string; error: string }> = [];

  // Find which functions are UI resource entry points — we'll skip those
  const resourceFunctionKeys = new Set<string>();
  for (const mod of manifest.uiModules) {
    // UI modules don't directly reference a function key — they reference a resource.
    // The resolver function IS what we want to load.
    // So we load ALL functions (resolvers, triggers, consumers) but skip resource imports.
  }

  for (const [fnKey, fnDef] of manifest.functions) {
    try {
      const { fileStem, exportName } = parseHandlerString(fnDef.handler);
      const filePath = await resolveHandlerFile(appDir, fileStem);

      if (!filePath) {
        errors.push({
          functionKey: fnKey,
          error: `Could not find handler file for "${fnDef.handler}"`,
        });
        continue;
      }

      const { pathToFileURL } = await import('node:url');
      const fileUrl = pathToFileURL(filePath).href;
      const mod = await import(fileUrl + '?t=' + Date.now());

      const handler = mod[exportName] ?? mod.default?.[exportName];
      if (!handler) {
        errors.push({
          functionKey: fnKey,
          error: `No export "${exportName}" in "${filePath}"`,
        });
        continue;
      }

      // Register as resolver
      if (typeof handler === 'object') {
        for (const [defKey, defHandler] of Object.entries(handler)) {
          if (typeof defHandler === 'function') {
            sim.resolver.define(defKey, defHandler as any);
          }
        }
      } else if (typeof handler === 'function') {
        sim.resolver.define(fnKey, handler);
      }

      loadedFunctions.push(fnKey);
    } catch (err: any) {
      errors.push({
        functionKey: fnKey,
        error: err.message,
      });
    }
  }

  // Wire up consumers
  for (const consumer of manifest.consumers) {
    const handlerMap = sim.resolver.getHandlerMap();
    const handler = handlerMap.get(consumer.functionKey);
    if (handler) {
      sim.registerConsumer(consumer.queue, handler as any);
    }
  }

  sim.loadManifestData(manifest);
  return { loadedFunctions, errors };
}

// ── Helpers (duplicated from deployer to avoid side effects) ────────────

function parseHandlerString(handler: string): { fileStem: string; exportName: string } {
  const lastDot = handler.lastIndexOf('.');
  if (lastDot === -1) return { fileStem: handler, exportName: 'default' };
  return {
    fileStem: handler.substring(0, lastDot),
    exportName: handler.substring(lastDot + 1),
  };
}

const FILE_EXTENSIONS = ['.js', '.ts', '.tsx', '.jsx', '.mjs', '.cjs'];

async function resolveHandlerFile(appDir: string, fileStem: string): Promise<string | null> {
  const { access } = await import('node:fs/promises');
  const srcDir = join(appDir, 'src');

  for (const ext of FILE_EXTENSIONS) {
    const candidate = resolve(srcDir, fileStem + ext);
    try { await access(candidate); return candidate; } catch {}
  }
  for (const ext of FILE_EXTENSIONS) {
    const candidate = resolve(appDir, fileStem + ext);
    try { await access(candidate); return candidate; } catch {}
  }
  return null;
}
